// License: CC-0

// WARNING: This file has automatically been generated on Sun, 18 Apr 2021 12:55:04 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package go_tpm2_tss provides CGo bindings for tpm2-tss. The package is automatically generated by "c-for-go".
*/
package cgo_tpm2_tss
