// License: CC-0

// WARNING: This file has automatically been generated on Fri, 16 Apr 2021 23:13:38 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

unsigned int TSS2_TCTI_TRANSMIT_FCN_3fb81c0d(TSS2_TCTI_CONTEXT* tctiContext, unsigned long int size, unsigned char* command) {
	return tss2TctiTransmitFcn3FB81C0D(tctiContext, size, command);
}

unsigned int TSS2_TCTI_RECEIVE_FCN_f4548f13(TSS2_TCTI_CONTEXT* tctiContext, unsigned long int* size, unsigned char* response, int timeout) {
	return tss2TctiReceiveFcnF4548F13(tctiContext, size, response, timeout);
}

void TSS2_TCTI_FINALIZE_FCN_f5e8712e(TSS2_TCTI_CONTEXT* tctiContext) {
	tss2TctiFinalizeFcnF5E8712E(tctiContext);
}

unsigned int TSS2_TCTI_CANCEL_FCN_900241eb(TSS2_TCTI_CONTEXT* tctiContext) {
	return tss2TctiCancelFcn900241EB(tctiContext);
}

unsigned int TSS2_TCTI_GET_POLL_HANDLES_FCN_d9753da9(TSS2_TCTI_CONTEXT* tctiContext, void* handles, unsigned long int* num_handles) {
	return tss2TctiGetPollHandlesFcnD9753DA9(tctiContext, handles, num_handles);
}

unsigned int TSS2_TCTI_SET_LOCALITY_FCN_47c1ecda(TSS2_TCTI_CONTEXT* tctiContext, unsigned char locality) {
	return tss2TctiSetLocalityFcn47C1ECDA(tctiContext, locality);
}

unsigned int TSS2_TCTI_MAKE_STICKY_FCN_de2406fc(TSS2_TCTI_CONTEXT* tctiContext, unsigned int* handle, unsigned char sticky) {
	return tss2TctiMakeStickyFcnDE2406FC(tctiContext, handle, sticky);
}

unsigned int TSS2_TCTI_INIT_FUNC_a5effe61(TSS2_TCTI_CONTEXT* tctiContext, unsigned long int* size, char* config) {
	return tss2TctiInitFuncA5EFFE61(tctiContext, size, config);
}

TSS2_TCTI_INFO* TSS2_TCTI_INFO_FUNC_3ab67cd0() {
	return tss2TctiInfoFunc3AB67CD0();
}

unsigned int Fapi_CB_Auth_4bc69268(FAPI_CONTEXT* context, char* description, char** auth, void* userData) {
	return fapiCbAuth4BC69268(context, description, auth, userData);
}

unsigned int Fapi_CB_Branch_a8bbee51(FAPI_CONTEXT* context, char* description, char** branchNames, unsigned long int numBranches, unsigned long int* selectedBranch, void* userData) {
	return fapiCbBranchA8BBEE51(context, description, branchNames, numBranches, selectedBranch, userData);
}

unsigned int Fapi_CB_Sign_2c66b3cf(FAPI_CONTEXT* context, char* description, char* publicKey, char* publicKeyHint, unsigned int hashAlg, unsigned char* dataToSign, unsigned long int dataToSignSize, unsigned char** signature, unsigned long int* signatureSize, void* userData) {
	return fapiCbSign2C66B3CF(context, description, publicKey, publicKeyHint, hashAlg, dataToSign, dataToSignSize, signature, signatureSize, userData);
}

unsigned int Fapi_CB_PolicyAction_d83965a7(FAPI_CONTEXT* context, char* action, void* userData) {
	return fapiCbPolicyactionD83965A7(context, action, userData);
}

int __compar_fn_t_60e030d6(void* arg0, void* arg1) {
	return _ComparFnT60E030D6(arg0, arg1);
}

char* TSS2_RC_HANDLER_c80e0a42(unsigned int rc) {
	return tss2RcHandlerC80E0A42(rc);
}

