// License: CC-0

// WARNING: This file has automatically been generated on Fri, 16 Apr 2021 23:18:11 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package go_tpm2_tss provides CGo bindings for tpm2-tss. The package is automatically generated by "c-for-go".
*/
package go_tpm2_tss
