// License: CC-0

// WARNING: This file has automatically been generated on Sat, 17 Apr 2021 00:39:05 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package go_tpm2_tss

/*
#cgo pkg-config: tss2-tcti-mssim tss2-tcti-device tss2-mu tss2-tctildr tss2-rc tss2-sys tss2-esys
#cgo CFLAGS: -I ../c/include
#include "tss2/tss2_common.h"
#include "tss2/tss2_esys.h"
#include "tss2/tss2_fapi.h"
#include "tss2/tss2_mu.h"
#include "tss2/tss2_rc.h"
#include "tss2/tss2_sys.h"
#include "tss2/tss2_tcti_device.h"
#include "tss2/tss2_tcti.h"
#include "tss2/tss2_tctildr.h"
#include "tss2/tss2_tcti_mssim.h"
#include "tss2/tss2_tcti_tbs.h"
#include "tss2/tss2_tpm2_types.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Uint8 type as declared in tss2/tss2_common.h:18
type Uint8 byte

// Byte type as declared in tss2/tss2_common.h:19
type Byte byte

// Int8 type as declared in tss2/tss2_common.h:20
type Int8 int8

// Bool type as declared in tss2/tss2_common.h:21
type Bool int32

// Uint16 type as declared in tss2/tss2_common.h:22
type Uint16 uint16

// Int16 type as declared in tss2/tss2_common.h:23
type Int16 int16

// Uint32 type as declared in tss2/tss2_common.h:24
type Uint32 uint32

// Int32 type as declared in tss2/tss2_common.h:25
type Int32 int32

// Uint64 type as declared in tss2/tss2_common.h:26
type Uint64 uint32

// Int64 type as declared in tss2/tss2_common.h:27
type Int64 int32

// Tss2AbiVersion as declared in tss2/tss2_common.h:37
type Tss2AbiVersion struct {
	Tsscreator     Uint32T
	Tssfamily      Uint32T
	Tsslevel       Uint32T
	Tssversion     Uint32T
	ref731c8581    *C.TSS2_ABI_VERSION
	allocs731c8581 interface{}
}

// Tss2Rc type as declared in tss2/tss2_common.h:45
type Tss2Rc uint32

// IntLeast8T type as declared in include/stdint.h:43
type IntLeast8T int8

// IntLeast16T type as declared in include/stdint.h:44
type IntLeast16T int16

// IntLeast32T type as declared in include/stdint.h:45
type IntLeast32T int32

// IntLeast64T type as declared in include/stdint.h:46
type IntLeast64T int32

// UintLeast8T type as declared in include/stdint.h:49
type UintLeast8T byte

// UintLeast16T type as declared in include/stdint.h:50
type UintLeast16T uint16

// UintLeast32T type as declared in include/stdint.h:51
type UintLeast32T uint32

// UintLeast64T type as declared in include/stdint.h:52
type UintLeast64T uint32

// IntFast8T type as declared in include/stdint.h:58
type IntFast8T int8

// IntFast16T type as declared in include/stdint.h:60
type IntFast16T int32

// IntFast32T type as declared in include/stdint.h:61
type IntFast32T int32

// IntFast64T type as declared in include/stdint.h:62
type IntFast64T int32

// UintFast8T type as declared in include/stdint.h:71
type UintFast8T byte

// UintFast16T type as declared in include/stdint.h:73
type UintFast16T uint32

// UintFast32T type as declared in include/stdint.h:74
type UintFast32T uint32

// UintFast64T type as declared in include/stdint.h:75
type UintFast64T uint32

// IntptrT type as declared in include/stdint.h:87
type IntptrT int32

// UintptrT type as declared in include/stdint.h:90
type UintptrT uint32

// IntmaxT type as declared in include/stdint.h:101
type IntmaxT int32

// UintmaxT type as declared in include/stdint.h:102
type UintmaxT uint32

// _UChar type as declared in bits/types.h:31
type _UChar byte

// _UShort type as declared in bits/types.h:32
type _UShort uint16

// _UInt type as declared in bits/types.h:33
type _UInt uint32

// _ULong type as declared in bits/types.h:34
type _ULong uint32

// _Int8T type as declared in bits/types.h:37
type _Int8T int8

// _Uint8T type as declared in bits/types.h:38
type _Uint8T byte

// _Int16T type as declared in bits/types.h:39
type _Int16T int16

// _Uint16T type as declared in bits/types.h:40
type _Uint16T uint16

// _Int32T type as declared in bits/types.h:41
type _Int32T int32

// _Uint32T type as declared in bits/types.h:42
type _Uint32T uint32

// _Int64T type as declared in bits/types.h:44
type _Int64T int32

// _Uint64T type as declared in bits/types.h:45
type _Uint64T uint32

// _IntLeast8T type as declared in bits/types.h:52
type _IntLeast8T int8

// _UintLeast8T type as declared in bits/types.h:53
type _UintLeast8T byte

// _IntLeast16T type as declared in bits/types.h:54
type _IntLeast16T int16

// _UintLeast16T type as declared in bits/types.h:55
type _UintLeast16T uint16

// _IntLeast32T type as declared in bits/types.h:56
type _IntLeast32T int32

// _UintLeast32T type as declared in bits/types.h:57
type _UintLeast32T uint32

// _IntLeast64T type as declared in bits/types.h:58
type _IntLeast64T int32

// _UintLeast64T type as declared in bits/types.h:59
type _UintLeast64T uint32

// _QuadT type as declared in bits/types.h:63
type _QuadT int32

// _UQuadT type as declared in bits/types.h:64
type _UQuadT uint32

// _IntmaxT type as declared in bits/types.h:72
type _IntmaxT int32

// _UintmaxT type as declared in bits/types.h:73
type _UintmaxT uint32

// _DevT type as declared in bits/types.h:145
type _DevT uint32

// _UidT type as declared in bits/types.h:146
type _UidT uint32

// _GidT type as declared in bits/types.h:147
type _GidT uint32

// _InoT type as declared in bits/types.h:148
type _InoT uint32

// _Ino64T type as declared in bits/types.h:149
type _Ino64T uint32

// _ModeT type as declared in bits/types.h:150
type _ModeT uint32

// _NlinkT type as declared in bits/types.h:151
type _NlinkT uint32

// _OffT type as declared in bits/types.h:152
type _OffT int32

// _Off64T type as declared in bits/types.h:153
type _Off64T int32

// _PidT type as declared in bits/types.h:154
type _PidT int32

// _FsidT as declared in bits/types.h:155
type _FsidT struct {
	_Val           [2]int32
	ref3fddfece    *C.__fsid_t
	allocs3fddfece interface{}
}

// _ClockT type as declared in bits/types.h:156
type _ClockT int32

// _RlimT type as declared in bits/types.h:157
type _RlimT uint32

// _Rlim64T type as declared in bits/types.h:158
type _Rlim64T uint32

// _IdT type as declared in bits/types.h:159
type _IdT uint32

// _TimeT type as declared in bits/types.h:160
type _TimeT int32

// _UsecondsT type as declared in bits/types.h:161
type _UsecondsT uint32

// _SusecondsT type as declared in bits/types.h:162
type _SusecondsT int32

// _DaddrT type as declared in bits/types.h:164
type _DaddrT int32

// _KeyT type as declared in bits/types.h:165
type _KeyT int32

// _ClockidT type as declared in bits/types.h:168
type _ClockidT int32

// _TimerT type as declared in bits/types.h:171
type _TimerT unsafe.Pointer

// _BlksizeT type as declared in bits/types.h:174
type _BlksizeT int32

// _BlkcntT type as declared in bits/types.h:179
type _BlkcntT int32

// _Blkcnt64T type as declared in bits/types.h:180
type _Blkcnt64T int32

// _FsblkcntT type as declared in bits/types.h:183
type _FsblkcntT uint32

// _Fsblkcnt64T type as declared in bits/types.h:184
type _Fsblkcnt64T uint32

// _FsfilcntT type as declared in bits/types.h:187
type _FsfilcntT uint32

// _Fsfilcnt64T type as declared in bits/types.h:188
type _Fsfilcnt64T uint32

// _FswordT type as declared in bits/types.h:191
type _FswordT int32

// _SsizeT type as declared in bits/types.h:193
type _SsizeT int32

// _SyscallSlongT type as declared in bits/types.h:196
type _SyscallSlongT int32

// _SyscallUlongT type as declared in bits/types.h:198
type _SyscallUlongT uint32

// _LoffT type as declared in bits/types.h:202
type _LoffT int32

// _CaddrT type as declared in bits/types.h:203
type _CaddrT []byte

// _IntptrT type as declared in bits/types.h:206
type _IntptrT int32

// _SocklenT type as declared in bits/types.h:209
type _SocklenT uint32

// _SigAtomicT type as declared in bits/types.h:214
type _SigAtomicT int32

// Int8T type as declared in bits/stdint-intn.h:24
type Int8T int8

// Int16T type as declared in bits/stdint-intn.h:25
type Int16T int16

// Int32T type as declared in bits/stdint-intn.h:26
type Int32T int32

// Int64T type as declared in bits/stdint-intn.h:27
type Int64T int32

// Uint8T type as declared in bits/stdint-uintn.h:24
type Uint8T byte

// Uint16T type as declared in bits/stdint-uintn.h:25
type Uint16T uint16

// Uint32T type as declared in bits/stdint-uintn.h:26
type Uint32T uint32

// Uint64T type as declared in bits/stdint-uintn.h:27
type Uint64T uint32

// EsysTr type as declared in tss2/tss2_esys.h:16
type EsysTr uint32

// EsysContext as declared in tss2/tss2_esys.h:66
type EsysContext C.ESYS_CONTEXT

// Tss2TctiPollHandle type as declared in tss2/tss2_tcti.h:57
type Tss2TctiPollHandle [0]byte

// Tss2TctiContext as declared in tss2/tss2_tcti.h:140
type Tss2TctiContext C.TSS2_TCTI_CONTEXT

// Tss2TctiTransmitFcn type as declared in tss2/tss2_tcti.h:146
type Tss2TctiTransmitFcn func(tcticontext *Tss2TctiContext, size SizeT, command []Uint8T) Tss2Rc

// Tss2TctiReceiveFcn type as declared in tss2/tss2_tcti.h:150
type Tss2TctiReceiveFcn func(tcticontext *Tss2TctiContext, size []SizeT, response []Uint8T, timeout Int32T) Tss2Rc

// Tss2TctiFinalizeFcn type as declared in tss2/tss2_tcti.h:155
type Tss2TctiFinalizeFcn func(tcticontext *Tss2TctiContext)

// Tss2TctiCancelFcn type as declared in tss2/tss2_tcti.h:157
type Tss2TctiCancelFcn func(tcticontext *Tss2TctiContext) Tss2Rc

// Tss2TctiGetPollHandlesFcn type as declared in tss2/tss2_tcti.h:159
type Tss2TctiGetPollHandlesFcn func(tcticontext *Tss2TctiContext, handles *Tss2TctiPollHandle, numHandles []SizeT) Tss2Rc

// Tss2TctiSetLocalityFcn type as declared in tss2/tss2_tcti.h:163
type Tss2TctiSetLocalityFcn func(tcticontext *Tss2TctiContext, locality Uint8T) Tss2Rc

// Tss2TctiMakeStickyFcn type as declared in tss2/tss2_tcti.h:166
type Tss2TctiMakeStickyFcn func(tcticontext *Tss2TctiContext, handle []Tpm2Handle, sticky Uint8T) Tss2Rc

// Tss2TctiInitFunc type as declared in tss2/tss2_tcti.h:170
type Tss2TctiInitFunc func(tcticontext *Tss2TctiContext, size []SizeT, config []string) Tss2Rc

// Tss2TctiContextCommonV1 as declared in tss2/tss2_tcti.h:185
type Tss2TctiContextCommonV1 struct {
	Magic          Uint64T
	Version        Uint32T
	Transmit       Tss2TctiTransmitFcn
	Receive        Tss2TctiReceiveFcn
	Finalize       Tss2TctiFinalizeFcn
	Cancel         Tss2TctiCancelFcn
	Getpollhandles Tss2TctiGetPollHandlesFcn
	Setlocality    Tss2TctiSetLocalityFcn
	ref6a31a31a    *C.TSS2_TCTI_CONTEXT_COMMON_V1
	allocs6a31a31a interface{}
}

// Tss2TctiContextCommonV2 as declared in tss2/tss2_tcti.h:190
type Tss2TctiContextCommonV2 struct {
	V1             Tss2TctiContextCommonV1
	Makesticky     Tss2TctiMakeStickyFcn
	reff338f2a0    *C.TSS2_TCTI_CONTEXT_COMMON_V2
	allocsf338f2a0 interface{}
}

// Tss2TctiContextCommonCurrent as declared in tss2/tss2_tcti.h:192
type Tss2TctiContextCommonCurrent struct {
	V1             Tss2TctiContextCommonV1
	Makesticky     Tss2TctiMakeStickyFcn
	reff338f2a0    *C.TSS2_TCTI_CONTEXT_COMMON_V2
	allocsf338f2a0 interface{}
}

// Tss2TctiInfo as declared in tss2/tss2_tcti.h:202
type Tss2TctiInfo struct {
	Version        Uint32T
	Name           []string
	Description    []string
	ConfigHelp     []string
	Init           Tss2TctiInitFunc
	ref39dad98b    *C.TSS2_TCTI_INFO
	allocs39dad98b interface{}
}

// Tss2TctiInfoFunc type as declared in tss2/tss2_tcti.h:204
type Tss2TctiInfoFunc func() *Tss2TctiInfo

// PtrdiffT type as declared in include/stddef.h:143
type PtrdiffT int32

// SizeT type as declared in include/stddef.h:209
type SizeT uint32

// WcharT type as declared in include/stddef.h:321
type WcharT int32

// Tpm2AlgId type as declared in tss2/tss2_tpm2_types.h:70
type Tpm2AlgId uint16

// Tpm2EccCurve type as declared in tss2/tss2_tpm2_types.h:117
type Tpm2EccCurve uint16

// Tpm2Cc type as declared in tss2/tss2_tpm2_types.h:129
type Tpm2Cc uint32

// Tpm2AlgorithmId type as declared in tss2/tss2_tpm2_types.h:250
type Tpm2AlgorithmId uint32

// Tpm2ModifierIndicator type as declared in tss2/tss2_tpm2_types.h:251
type Tpm2ModifierIndicator uint32

// Tpm2AuthorizationSize type as declared in tss2/tss2_tpm2_types.h:252
type Tpm2AuthorizationSize uint32

// Tpm2ParameterSize type as declared in tss2/tss2_tpm2_types.h:253
type Tpm2ParameterSize uint32

// Tpm2KeySize type as declared in tss2/tss2_tpm2_types.h:254
type Tpm2KeySize uint16

// Tpm2KeyBits type as declared in tss2/tss2_tpm2_types.h:255
type Tpm2KeyBits uint16

// Tpm2Spec type as declared in tss2/tss2_tpm2_types.h:258
type Tpm2Spec uint32

// Tpm2Generated type as declared in tss2/tss2_tpm2_types.h:266
type Tpm2Generated uint32

// Tpm2Rc type as declared in tss2/tss2_tpm2_types.h:270
type Tpm2Rc uint32

// Tpm2ClockAdjust type as declared in tss2/tss2_tpm2_types.h:394
type Tpm2ClockAdjust int8

// Tpm2Eo type as declared in tss2/tss2_tpm2_types.h:404
type Tpm2Eo uint16

// Tpm2St type as declared in tss2/tss2_tpm2_types.h:419
type Tpm2St uint16

// Tpm2Su type as declared in tss2/tss2_tpm2_types.h:442
type Tpm2Su uint16

// Tpm2Se type as declared in tss2/tss2_tpm2_types.h:447
type Tpm2Se byte

// Tpm2Cap type as declared in tss2/tss2_tpm2_types.h:453
type Tpm2Cap uint32

// Tpm2Pt type as declared in tss2/tss2_tpm2_types.h:468
type Tpm2Pt uint32

// Tpm2PtPcr type as declared in tss2/tss2_tpm2_types.h:542
type Tpm2PtPcr uint32

// Tpm2Ps type as declared in tss2/tss2_tpm2_types.h:576
type Tpm2Ps uint32

// Tpm2Handle type as declared in tss2/tss2_tpm2_types.h:595
type Tpm2Handle uint32

// Tpm2Ht type as declared in tss2/tss2_tpm2_types.h:598
type Tpm2Ht byte

// Tpm2Rh type as declared in tss2/tss2_tpm2_types.h:610
type Tpm2Rh uint32

// Tpm2Hc type as declared in tss2/tss2_tpm2_types.h:631
type Tpm2Hc uint32

// TpmaAlgorithm type as declared in tss2/tss2_tpm2_types.h:663
type TpmaAlgorithm uint32

// TpmaObject type as declared in tss2/tss2_tpm2_types.h:676
type TpmaObject uint32

// TpmaSession type as declared in tss2/tss2_tpm2_types.h:696
type TpmaSession byte

// TpmaLocality type as declared in tss2/tss2_tpm2_types.h:707
type TpmaLocality byte

// TpmaPermanent type as declared in tss2/tss2_tpm2_types.h:718
type TpmaPermanent uint32

// TpmaStartupClear type as declared in tss2/tss2_tpm2_types.h:730
type TpmaStartupClear uint32

// TpmaMemory type as declared in tss2/tss2_tpm2_types.h:740
type TpmaMemory uint32

// TpmaCc type as declared in tss2/tss2_tpm2_types.h:748
type TpmaCc uint32

// TpmaModes type as declared in tss2/tss2_tpm2_types.h:764
type TpmaModes uint32

// TpmiYesNo type as declared in tss2/tss2_tpm2_types.h:770
type TpmiYesNo byte

// TpmiDhObject type as declared in tss2/tss2_tpm2_types.h:775
type TpmiDhObject uint32

// TpmiDhPersistent type as declared in tss2/tss2_tpm2_types.h:778
type TpmiDhPersistent uint32

// TpmiDhEntity type as declared in tss2/tss2_tpm2_types.h:781
type TpmiDhEntity uint32

// TpmiDhPcr type as declared in tss2/tss2_tpm2_types.h:784
type TpmiDhPcr uint32

// TpmiShAuthSession type as declared in tss2/tss2_tpm2_types.h:787
type TpmiShAuthSession uint32

// TpmiShHmac type as declared in tss2/tss2_tpm2_types.h:790
type TpmiShHmac uint32

// TpmiShPolicy type as declared in tss2/tss2_tpm2_types.h:793
type TpmiShPolicy uint32

// TpmiDhContext type as declared in tss2/tss2_tpm2_types.h:796
type TpmiDhContext uint32

// TpmiRhHierarchy type as declared in tss2/tss2_tpm2_types.h:799
type TpmiRhHierarchy uint32

// TpmiRhEnables type as declared in tss2/tss2_tpm2_types.h:802
type TpmiRhEnables uint32

// TpmiRhHierarchyAuth type as declared in tss2/tss2_tpm2_types.h:805
type TpmiRhHierarchyAuth uint32

// TpmiRhPlatform type as declared in tss2/tss2_tpm2_types.h:808
type TpmiRhPlatform uint32

// TpmiRhOwner type as declared in tss2/tss2_tpm2_types.h:811
type TpmiRhOwner uint32

// TpmiRhEndorsement type as declared in tss2/tss2_tpm2_types.h:814
type TpmiRhEndorsement uint32

// TpmiRhProvision type as declared in tss2/tss2_tpm2_types.h:817
type TpmiRhProvision uint32

// TpmiRhClear type as declared in tss2/tss2_tpm2_types.h:820
type TpmiRhClear uint32

// TpmiRhNvAuth type as declared in tss2/tss2_tpm2_types.h:823
type TpmiRhNvAuth uint32

// TpmiRhLockout type as declared in tss2/tss2_tpm2_types.h:826
type TpmiRhLockout uint32

// TpmiRhNvIndex type as declared in tss2/tss2_tpm2_types.h:829
type TpmiRhNvIndex uint32

// TpmiAlgHash type as declared in tss2/tss2_tpm2_types.h:832
type TpmiAlgHash uint16

// TpmiAlgAsym type as declared in tss2/tss2_tpm2_types.h:835
type TpmiAlgAsym uint16

// TpmiAlgSym type as declared in tss2/tss2_tpm2_types.h:838
type TpmiAlgSym uint16

// TpmiAlgSymObject type as declared in tss2/tss2_tpm2_types.h:841
type TpmiAlgSymObject uint16

// TpmiAlgSymMode type as declared in tss2/tss2_tpm2_types.h:844
type TpmiAlgSymMode uint16

// TpmiAlgKdf type as declared in tss2/tss2_tpm2_types.h:847
type TpmiAlgKdf uint16

// TpmiAlgSigScheme type as declared in tss2/tss2_tpm2_types.h:850
type TpmiAlgSigScheme uint16

// TpmiEccKeyExchange type as declared in tss2/tss2_tpm2_types.h:853
type TpmiEccKeyExchange uint16

// TpmiStCommandTag type as declared in tss2/tss2_tpm2_types.h:856
type TpmiStCommandTag uint16

// TpmsEmpty as declared in tss2/tss2_tpm2_types.h:861
type TpmsEmpty struct {
	Empty          [1]Byte
	ref25eb996f    *C.TPMS_EMPTY
	allocs25eb996f interface{}
}

// TpmsAlgorithmDescription as declared in tss2/tss2_tpm2_types.h:867
type TpmsAlgorithmDescription struct {
	Alg            Tpm2AlgId
	Attributes     TpmaAlgorithm
	ref3b72095b    *C.TPMS_ALGORITHM_DESCRIPTION
	allocs3b72095b interface{}
}

// TpmuHa as declared in tss2/tss2_tpm2_types.h:876
const sizeofTpmuHa = unsafe.Sizeof(C.TPMU_HA{})

type TpmuHa [sizeofTpmuHa]byte

// TpmtHa as declared in tss2/tss2_tpm2_types.h:882
type TpmtHa struct {
	Hashalg        TpmiAlgHash
	Digest         TpmuHa
	reffcefc3a6    *C.TPMT_HA
	allocsfcefc3a6 interface{}
}

// Tpm2bDigest as declared in tss2/tss2_tpm2_types.h:888
type Tpm2bDigest struct {
	Size           Uint16
	Buffer         [64]Byte
	refa5988425    *C.TPM2B_DIGEST
	allocsa5988425 interface{}
}

// Tpm2bData as declared in tss2/tss2_tpm2_types.h:894
type Tpm2bData struct {
	Size           Uint16
	Buffer         [64]Byte
	refeeb25ec3    *C.TPM2B_DATA
	allocseeb25ec3 interface{}
}

// Tpm2bNonce as declared in tss2/tss2_tpm2_types.h:897
type Tpm2bNonce struct {
	Size           Uint16
	Buffer         [64]Byte
	refa5988425    *C.TPM2B_DIGEST
	allocsa5988425 interface{}
}

// Tpm2bAuth as declared in tss2/tss2_tpm2_types.h:900
type Tpm2bAuth struct {
	Size           Uint16
	Buffer         [64]Byte
	refa5988425    *C.TPM2B_DIGEST
	allocsa5988425 interface{}
}

// Tpm2bOperand as declared in tss2/tss2_tpm2_types.h:903
type Tpm2bOperand struct {
	Size           Uint16
	Buffer         [64]Byte
	refa5988425    *C.TPM2B_DIGEST
	allocsa5988425 interface{}
}

// Tpm2bEvent as declared in tss2/tss2_tpm2_types.h:909
type Tpm2bEvent struct {
	Size           Uint16
	Buffer         [1024]Byte
	refd655c82a    *C.TPM2B_EVENT
	allocsd655c82a interface{}
}

// Tpm2bMaxBuffer as declared in tss2/tss2_tpm2_types.h:915
type Tpm2bMaxBuffer struct {
	Size           Uint16
	Buffer         [1024]Byte
	ref59a18869    *C.TPM2B_MAX_BUFFER
	allocs59a18869 interface{}
}

// Tpm2bMaxNvBuffer as declared in tss2/tss2_tpm2_types.h:921
type Tpm2bMaxNvBuffer struct {
	Size           Uint16
	Buffer         [2048]Byte
	ref2847ea85    *C.TPM2B_MAX_NV_BUFFER
	allocs2847ea85 interface{}
}

// Tpm2bTimeout as declared in tss2/tss2_tpm2_types.h:924
type Tpm2bTimeout struct {
	Size           Uint16
	Buffer         [64]Byte
	refa5988425    *C.TPM2B_DIGEST
	allocsa5988425 interface{}
}

// Tpm2bIv as declared in tss2/tss2_tpm2_types.h:930
type Tpm2bIv struct {
	Size          Uint16
	Buffer        [16]Byte
	refaf2c000    *C.TPM2B_IV
	allocsaf2c000 interface{}
}

// TpmuName as declared in tss2/tss2_tpm2_types.h:936
const sizeofTpmuName = unsafe.Sizeof(C.TPMU_NAME{})

type TpmuName [sizeofTpmuName]byte

// Tpm2bName as declared in tss2/tss2_tpm2_types.h:942
type Tpm2bName struct {
	Size           Uint16
	Name           [68]Byte
	ref1d62d3a6    *C.TPM2B_NAME
	allocs1d62d3a6 interface{}
}

// TpmsPcrSelect as declared in tss2/tss2_tpm2_types.h:948
type TpmsPcrSelect struct {
	Sizeofselect   Uint8
	Pcrselect      [4]Byte
	ref3862416a    *C.TPMS_PCR_SELECT
	allocs3862416a interface{}
}

// TpmsPcrSelection as declared in tss2/tss2_tpm2_types.h:955
type TpmsPcrSelection struct {
	Hash           TpmiAlgHash
	Sizeofselect   Uint8
	Pcrselect      [4]Byte
	ref691160fe    *C.TPMS_PCR_SELECTION
	allocs691160fe interface{}
}

// TpmtTkCreation as declared in tss2/tss2_tpm2_types.h:962
type TpmtTkCreation struct {
	Tag            Tpm2St
	Hierarchy      TpmiRhHierarchy
	Digest         Tpm2bDigest
	reff8fc2eb3    *C.TPMT_TK_CREATION
	allocsf8fc2eb3 interface{}
}

// TpmtTkVerified as declared in tss2/tss2_tpm2_types.h:969
type TpmtTkVerified struct {
	Tag            Tpm2St
	Hierarchy      TpmiRhHierarchy
	Digest         Tpm2bDigest
	refa05754de    *C.TPMT_TK_VERIFIED
	allocsa05754de interface{}
}

// TpmtTkAuth as declared in tss2/tss2_tpm2_types.h:976
type TpmtTkAuth struct {
	Tag            Tpm2St
	Hierarchy      TpmiRhHierarchy
	Digest         Tpm2bDigest
	ref13a3ead8    *C.TPMT_TK_AUTH
	allocs13a3ead8 interface{}
}

// TpmtTkHashcheck as declared in tss2/tss2_tpm2_types.h:983
type TpmtTkHashcheck struct {
	Tag            Tpm2St
	Hierarchy      TpmiRhHierarchy
	Digest         Tpm2bDigest
	refe0b9eec8    *C.TPMT_TK_HASHCHECK
	allocse0b9eec8 interface{}
}

// TpmsAlgProperty as declared in tss2/tss2_tpm2_types.h:989
type TpmsAlgProperty struct {
	Alg            Tpm2AlgId
	Algproperties  TpmaAlgorithm
	reff5365ade    *C.TPMS_ALG_PROPERTY
	allocsf5365ade interface{}
}

// TpmsTaggedProperty as declared in tss2/tss2_tpm2_types.h:995
type TpmsTaggedProperty struct {
	Property       Tpm2Pt
	Value          Uint32
	ref3544866c    *C.TPMS_TAGGED_PROPERTY
	allocs3544866c interface{}
}

// TpmsTaggedPcrSelect as declared in tss2/tss2_tpm2_types.h:1002
type TpmsTaggedPcrSelect struct {
	Tag            Tpm2PtPcr
	Sizeofselect   Uint8
	Pcrselect      [4]Byte
	ref168b217f    *C.TPMS_TAGGED_PCR_SELECT
	allocs168b217f interface{}
}

// TpmsTaggedPolicy as declared in tss2/tss2_tpm2_types.h:1008
type TpmsTaggedPolicy struct {
	Handle         Tpm2Handle
	Policyhash     TpmtHa
	refc72d4bc6    *C.TPMS_TAGGED_POLICY
	allocsc72d4bc6 interface{}
}

// TpmlCc as declared in tss2/tss2_tpm2_types.h:1014
type TpmlCc struct {
	Count          Uint32
	Commandcodes   [256]Tpm2Cc
	ref64b80431    *C.TPML_CC
	allocs64b80431 interface{}
}

// TpmlCca as declared in tss2/tss2_tpm2_types.h:1020
type TpmlCca struct {
	Count             Uint32
	Commandattributes [256]TpmaCc
	ref826326b5       *C.TPML_CCA
	allocs826326b5    interface{}
}

// TpmlAlg as declared in tss2/tss2_tpm2_types.h:1026
type TpmlAlg struct {
	Count          Uint32
	Algorithms     [128]Tpm2AlgId
	refef1c4b21    *C.TPML_ALG
	allocsef1c4b21 interface{}
}

// TpmlHandle as declared in tss2/tss2_tpm2_types.h:1032
type TpmlHandle struct {
	Count          Uint32
	Handle         [254]Tpm2Handle
	ref4e3c7552    *C.TPML_HANDLE
	allocs4e3c7552 interface{}
}

// TpmlDigest as declared in tss2/tss2_tpm2_types.h:1038
type TpmlDigest struct {
	Count          Uint32
	Digests        [8]Tpm2bDigest
	refd2aef539    *C.TPML_DIGEST
	allocsd2aef539 interface{}
}

// TpmlDigestValues as declared in tss2/tss2_tpm2_types.h:1044
type TpmlDigestValues struct {
	Count         Uint32
	Digests       [16]TpmtHa
	ref882542d    *C.TPML_DIGEST_VALUES
	allocs882542d interface{}
}

// TpmlPcrSelection as declared in tss2/tss2_tpm2_types.h:1050
type TpmlPcrSelection struct {
	Count          Uint32
	Pcrselections  [16]TpmsPcrSelection
	ref79fb3c2c    *C.TPML_PCR_SELECTION
	allocs79fb3c2c interface{}
}

// TpmlAlgProperty as declared in tss2/tss2_tpm2_types.h:1056
type TpmlAlgProperty struct {
	Count          Uint32
	Algproperties  [127]TpmsAlgProperty
	refc510d244    *C.TPML_ALG_PROPERTY
	allocsc510d244 interface{}
}

// TpmlTaggedTpmProperty as declared in tss2/tss2_tpm2_types.h:1062
type TpmlTaggedTpmProperty struct {
	Count          Uint32
	Tpmproperty    [127]TpmsTaggedProperty
	refafb53290    *C.TPML_TAGGED_TPM_PROPERTY
	allocsafb53290 interface{}
}

// TpmlTaggedPcrProperty as declared in tss2/tss2_tpm2_types.h:1068
type TpmlTaggedPcrProperty struct {
	Count          Uint32
	Pcrproperty    [84]TpmsTaggedPcrSelect
	ref4d027140    *C.TPML_TAGGED_PCR_PROPERTY
	allocs4d027140 interface{}
}

// TpmlEccCurve as declared in tss2/tss2_tpm2_types.h:1074
type TpmlEccCurve struct {
	Count         Uint32
	Ecccurves     [508]Tpm2EccCurve
	ref1d4d459    *C.TPML_ECC_CURVE
	allocs1d4d459 interface{}
}

// TpmlIntelPttProperty as declared in tss2/tss2_tpm2_types.h:1080
type TpmlIntelPttProperty struct {
	Count          Uint32
	Property       [256]Uint32
	ref8d735f38    *C.TPML_INTEL_PTT_PROPERTY
	allocs8d735f38 interface{}
}

// TpmuCapabilities as declared in tss2/tss2_tpm2_types.h:1094
const sizeofTpmuCapabilities = unsafe.Sizeof(C.TPMU_CAPABILITIES{})

type TpmuCapabilities [sizeofTpmuCapabilities]byte

// TpmsCapabilityData as declared in tss2/tss2_tpm2_types.h:1100
type TpmsCapabilityData struct {
	Capability     Tpm2Cap
	Data           TpmuCapabilities
	ref67ad78ab    *C.TPMS_CAPABILITY_DATA
	allocs67ad78ab interface{}
}

// TpmsClockInfo as declared in tss2/tss2_tpm2_types.h:1108
type TpmsClockInfo struct {
	Clock          Uint64
	Resetcount     Uint32
	Restartcount   Uint32
	Safe           TpmiYesNo
	ref65ce4bbf    *C.TPMS_CLOCK_INFO
	allocs65ce4bbf interface{}
}

// TpmsTimeInfo as declared in tss2/tss2_tpm2_types.h:1114
type TpmsTimeInfo struct {
	Time           Uint64
	Clockinfo      TpmsClockInfo
	refe427c7f1    *C.TPMS_TIME_INFO
	allocse427c7f1 interface{}
}

// TpmsTimeAttestInfo as declared in tss2/tss2_tpm2_types.h:1120
type TpmsTimeAttestInfo struct {
	Time            TpmsTimeInfo
	Firmwareversion Uint64
	ref3f48111      *C.TPMS_TIME_ATTEST_INFO
	allocs3f48111   interface{}
}

// TpmsCertifyInfo as declared in tss2/tss2_tpm2_types.h:1126
type TpmsCertifyInfo struct {
	Name           Tpm2bName
	Qualifiedname  Tpm2bName
	ref55e2ea11    *C.TPMS_CERTIFY_INFO
	allocs55e2ea11 interface{}
}

// TpmsQuoteInfo as declared in tss2/tss2_tpm2_types.h:1132
type TpmsQuoteInfo struct {
	Pcrselect      TpmlPcrSelection
	Pcrdigest      Tpm2bDigest
	refde852d70    *C.TPMS_QUOTE_INFO
	allocsde852d70 interface{}
}

// TpmsCommandAuditInfo as declared in tss2/tss2_tpm2_types.h:1140
type TpmsCommandAuditInfo struct {
	Auditcounter   Uint64
	Digestalg      Tpm2AlgId
	Auditdigest    Tpm2bDigest
	Commanddigest  Tpm2bDigest
	ref73825a84    *C.TPMS_COMMAND_AUDIT_INFO
	allocs73825a84 interface{}
}

// TpmsSessionAuditInfo as declared in tss2/tss2_tpm2_types.h:1146
type TpmsSessionAuditInfo struct {
	Exclusivesession TpmiYesNo
	Sessiondigest    Tpm2bDigest
	ref441b918       *C.TPMS_SESSION_AUDIT_INFO
	allocs441b918    interface{}
}

// TpmsCreationInfo as declared in tss2/tss2_tpm2_types.h:1152
type TpmsCreationInfo struct {
	Objectname     Tpm2bName
	Creationhash   Tpm2bDigest
	ref85c39129    *C.TPMS_CREATION_INFO
	allocs85c39129 interface{}
}

// TpmsNvCertifyInfo as declared in tss2/tss2_tpm2_types.h:1159
type TpmsNvCertifyInfo struct {
	Indexname      Tpm2bName
	Offset         Uint16
	Nvcontents     Tpm2bMaxNvBuffer
	ref24c11787    *C.TPMS_NV_CERTIFY_INFO
	allocs24c11787 interface{}
}

// TpmiStAttest type as declared in tss2/tss2_tpm2_types.h:1162
type TpmiStAttest uint16

// TpmuAttest as declared in tss2/tss2_tpm2_types.h:1173
const sizeofTpmuAttest = unsafe.Sizeof(C.TPMU_ATTEST{})

type TpmuAttest [sizeofTpmuAttest]byte

// TpmsAttest as declared in tss2/tss2_tpm2_types.h:1184
type TpmsAttest struct {
	Magic           Tpm2Generated
	Type            TpmiStAttest
	Qualifiedsigner Tpm2bName
	Extradata       Tpm2bData
	Clockinfo       TpmsClockInfo
	Firmwareversion Uint64
	Attested        TpmuAttest
	reffd24ec4f     *C.TPMS_ATTEST
	allocsfd24ec4f  interface{}
}

// Tpm2bAttest as declared in tss2/tss2_tpm2_types.h:1190
type Tpm2bAttest struct {
	Size            Uint16
	Attestationdata [2304]Byte
	ref2f89bed4     *C.TPM2B_ATTEST
	allocs2f89bed4  interface{}
}

// TpmsAuthCommand as declared in tss2/tss2_tpm2_types.h:1198
type TpmsAuthCommand struct {
	Sessionhandle     TpmiShAuthSession
	Nonce             Tpm2bNonce
	Sessionattributes TpmaSession
	Hmac              Tpm2bAuth
	refacb3c0e2       *C.TPMS_AUTH_COMMAND
	allocsacb3c0e2    interface{}
}

// TpmsAuthResponse as declared in tss2/tss2_tpm2_types.h:1205
type TpmsAuthResponse struct {
	Nonce             Tpm2bNonce
	Sessionattributes TpmaSession
	Hmac              Tpm2bAuth
	refca8dc780       *C.TPMS_AUTH_RESPONSE
	allocsca8dc780    interface{}
}

// TpmiAesKeyBits type as declared in tss2/tss2_tpm2_types.h:1208
type TpmiAesKeyBits uint16

// TpmiSm4KeyBits type as declared in tss2/tss2_tpm2_types.h:1211
type TpmiSm4KeyBits uint16

// TpmiCamelliaKeyBits type as declared in tss2/tss2_tpm2_types.h:1214
type TpmiCamelliaKeyBits uint16

// TpmuSymKeyBits as declared in tss2/tss2_tpm2_types.h:1223
const sizeofTpmuSymKeyBits = unsafe.Sizeof(C.TPMU_SYM_KEY_BITS{})

type TpmuSymKeyBits [sizeofTpmuSymKeyBits]byte

// TpmuSymMode as declared in tss2/tss2_tpm2_types.h:1231
const sizeofTpmuSymMode = unsafe.Sizeof(C.TPMU_SYM_MODE{})

type TpmuSymMode [sizeofTpmuSymMode]byte

// TpmtSymDef as declared in tss2/tss2_tpm2_types.h:1238
type TpmtSymDef struct {
	Algorithm      TpmiAlgSym
	Keybits        TpmuSymKeyBits
	Mode           TpmuSymMode
	ref9b7954d8    *C.TPMT_SYM_DEF
	allocs9b7954d8 interface{}
}

// TpmtSymDefObject as declared in tss2/tss2_tpm2_types.h:1245
type TpmtSymDefObject struct {
	Algorithm      TpmiAlgSymObject
	Keybits        TpmuSymKeyBits
	Mode           TpmuSymMode
	ref30d66831    *C.TPMT_SYM_DEF_OBJECT
	allocs30d66831 interface{}
}

// Tpm2bSymKey as declared in tss2/tss2_tpm2_types.h:1251
type Tpm2bSymKey struct {
	Size           Uint16
	Buffer         [32]Byte
	ref1e439447    *C.TPM2B_SYM_KEY
	allocs1e439447 interface{}
}

// TpmsSymcipherParms as declared in tss2/tss2_tpm2_types.h:1256
type TpmsSymcipherParms struct {
	Sym            TpmtSymDefObject
	refed33801d    *C.TPMS_SYMCIPHER_PARMS
	allocsed33801d interface{}
}

// Tpm2bSensitiveData as declared in tss2/tss2_tpm2_types.h:1262
type Tpm2bSensitiveData struct {
	Size           Uint16
	Buffer         [256]Byte
	refba9ff458    *C.TPM2B_SENSITIVE_DATA
	allocsba9ff458 interface{}
}

// TpmsSensitiveCreate as declared in tss2/tss2_tpm2_types.h:1268
type TpmsSensitiveCreate struct {
	Userauth       Tpm2bAuth
	Data           Tpm2bSensitiveData
	refeb1173b9    *C.TPMS_SENSITIVE_CREATE
	allocseb1173b9 interface{}
}

// Tpm2bSensitiveCreate as declared in tss2/tss2_tpm2_types.h:1274
type Tpm2bSensitiveCreate struct {
	Size           Uint16
	Sensitive      TpmsSensitiveCreate
	ref83ea8966    *C.TPM2B_SENSITIVE_CREATE
	allocs83ea8966 interface{}
}

// TpmsSchemeHash as declared in tss2/tss2_tpm2_types.h:1279
type TpmsSchemeHash struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSchemeEcdaa as declared in tss2/tss2_tpm2_types.h:1285
type TpmsSchemeEcdaa struct {
	Hashalg        TpmiAlgHash
	Count          Uint16
	refb9002c96    *C.TPMS_SCHEME_ECDAA
	allocsb9002c96 interface{}
}

// TpmiAlgKeyedhashScheme type as declared in tss2/tss2_tpm2_types.h:1288
type TpmiAlgKeyedhashScheme uint16

// TpmsSchemeHmac as declared in tss2/tss2_tpm2_types.h:1291
type TpmsSchemeHmac struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSchemeXor as declared in tss2/tss2_tpm2_types.h:1297
type TpmsSchemeXor struct {
	Hashalg        TpmiAlgHash
	Kdf            TpmiAlgKdf
	refd7d8558a    *C.TPMS_SCHEME_XOR
	allocsd7d8558a interface{}
}

// TpmuSchemeKeyedhash as declared in tss2/tss2_tpm2_types.h:1303
const sizeofTpmuSchemeKeyedhash = unsafe.Sizeof(C.TPMU_SCHEME_KEYEDHASH{})

type TpmuSchemeKeyedhash [sizeofTpmuSchemeKeyedhash]byte

// TpmtKeyedhashScheme as declared in tss2/tss2_tpm2_types.h:1309
type TpmtKeyedhashScheme struct {
	Scheme         TpmiAlgKeyedhashScheme
	Details        TpmuSchemeKeyedhash
	ref40a5159f    *C.TPMT_KEYEDHASH_SCHEME
	allocs40a5159f interface{}
}

// TpmsSigSchemeRsassa as declared in tss2/tss2_tpm2_types.h:1312
type TpmsSigSchemeRsassa struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSigSchemeRsapss as declared in tss2/tss2_tpm2_types.h:1313
type TpmsSigSchemeRsapss struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSigSchemeEcdsa as declared in tss2/tss2_tpm2_types.h:1316
type TpmsSigSchemeEcdsa struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSigSchemeSm2 as declared in tss2/tss2_tpm2_types.h:1317
type TpmsSigSchemeSm2 struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSigSchemeEcschnorr as declared in tss2/tss2_tpm2_types.h:1318
type TpmsSigSchemeEcschnorr struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSigSchemeEcdaa as declared in tss2/tss2_tpm2_types.h:1319
type TpmsSigSchemeEcdaa struct {
	Hashalg        TpmiAlgHash
	Count          Uint16
	refb9002c96    *C.TPMS_SCHEME_ECDAA
	allocsb9002c96 interface{}
}

// TpmuSigScheme as declared in tss2/tss2_tpm2_types.h:1331
const sizeofTpmuSigScheme = unsafe.Sizeof(C.TPMU_SIG_SCHEME{})

type TpmuSigScheme [sizeofTpmuSigScheme]byte

// TpmtSigScheme as declared in tss2/tss2_tpm2_types.h:1337
type TpmtSigScheme struct {
	Scheme         TpmiAlgSigScheme
	Details        TpmuSigScheme
	reff2a9c9bc    *C.TPMT_SIG_SCHEME
	allocsf2a9c9bc interface{}
}

// TpmsEncSchemeOaep as declared in tss2/tss2_tpm2_types.h:1340
type TpmsEncSchemeOaep struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsEncSchemeRsaes as declared in tss2/tss2_tpm2_types.h:1341
type TpmsEncSchemeRsaes struct {
	Empty          [1]Byte
	ref25eb996f    *C.TPMS_EMPTY
	allocs25eb996f interface{}
}

// TpmsKeySchemeEcdh as declared in tss2/tss2_tpm2_types.h:1344
type TpmsKeySchemeEcdh struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsKeySchemeEcmqv as declared in tss2/tss2_tpm2_types.h:1345
type TpmsKeySchemeEcmqv struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSchemeMgf1 as declared in tss2/tss2_tpm2_types.h:1348
type TpmsSchemeMgf1 struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSchemeKdf1Sp80056a as declared in tss2/tss2_tpm2_types.h:1349
type TpmsSchemeKdf1Sp80056a struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSchemeKdf2 as declared in tss2/tss2_tpm2_types.h:1350
type TpmsSchemeKdf2 struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmsSchemeKdf1Sp800108 as declared in tss2/tss2_tpm2_types.h:1351
type TpmsSchemeKdf1Sp800108 struct {
	Hashalg        TpmiAlgHash
	refe423df90    *C.TPMS_SCHEME_HASH
	allocse423df90 interface{}
}

// TpmuKdfScheme as declared in tss2/tss2_tpm2_types.h:1359
const sizeofTpmuKdfScheme = unsafe.Sizeof(C.TPMU_KDF_SCHEME{})

type TpmuKdfScheme [sizeofTpmuKdfScheme]byte

// TpmtKdfScheme as declared in tss2/tss2_tpm2_types.h:1365
type TpmtKdfScheme struct {
	Scheme         TpmiAlgKdf
	Details        TpmuKdfScheme
	reffb35ef69    *C.TPMT_KDF_SCHEME
	allocsfb35ef69 interface{}
}

// TpmiAlgAsymScheme type as declared in tss2/tss2_tpm2_types.h:1368
type TpmiAlgAsymScheme uint16

// TpmuAsymScheme as declared in tss2/tss2_tpm2_types.h:1383
const sizeofTpmuAsymScheme = unsafe.Sizeof(C.TPMU_ASYM_SCHEME{})

type TpmuAsymScheme [sizeofTpmuAsymScheme]byte

// TpmtAsymScheme as declared in tss2/tss2_tpm2_types.h:1389
type TpmtAsymScheme struct {
	Scheme        TpmiAlgAsymScheme
	Details       TpmuAsymScheme
	refd1d95f1    *C.TPMT_ASYM_SCHEME
	allocsd1d95f1 interface{}
}

// TpmiAlgRsaScheme type as declared in tss2/tss2_tpm2_types.h:1392
type TpmiAlgRsaScheme uint16

// TpmtRsaScheme as declared in tss2/tss2_tpm2_types.h:1398
type TpmtRsaScheme struct {
	Scheme         TpmiAlgRsaScheme
	Details        TpmuAsymScheme
	refe2ea63ea    *C.TPMT_RSA_SCHEME
	allocse2ea63ea interface{}
}

// TpmiAlgRsaDecrypt type as declared in tss2/tss2_tpm2_types.h:1401
type TpmiAlgRsaDecrypt uint16

// TpmtRsaDecrypt as declared in tss2/tss2_tpm2_types.h:1407
type TpmtRsaDecrypt struct {
	Scheme         TpmiAlgRsaDecrypt
	Details        TpmuAsymScheme
	ref1c9d69b7    *C.TPMT_RSA_DECRYPT
	allocs1c9d69b7 interface{}
}

// Tpm2bPublicKeyRsa as declared in tss2/tss2_tpm2_types.h:1413
type Tpm2bPublicKeyRsa struct {
	Size           Uint16
	Buffer         [512]Byte
	ref67f84e1f    *C.TPM2B_PUBLIC_KEY_RSA
	allocs67f84e1f interface{}
}

// TpmiRsaKeyBits type as declared in tss2/tss2_tpm2_types.h:1416
type TpmiRsaKeyBits uint16

// Tpm2bPrivateKeyRsa as declared in tss2/tss2_tpm2_types.h:1422
type Tpm2bPrivateKeyRsa struct {
	Size           Uint16
	Buffer         [256]Byte
	refa4047900    *C.TPM2B_PRIVATE_KEY_RSA
	allocsa4047900 interface{}
}

// Tpm2bEccParameter as declared in tss2/tss2_tpm2_types.h:1428
type Tpm2bEccParameter struct {
	Size           Uint16
	Buffer         [128]Byte
	refbb1052f4    *C.TPM2B_ECC_PARAMETER
	allocsbb1052f4 interface{}
}

// TpmsEccPoint as declared in tss2/tss2_tpm2_types.h:1434
type TpmsEccPoint struct {
	X              Tpm2bEccParameter
	Y              Tpm2bEccParameter
	refdce64ac7    *C.TPMS_ECC_POINT
	allocsdce64ac7 interface{}
}

// Tpm2bEccPoint as declared in tss2/tss2_tpm2_types.h:1440
type Tpm2bEccPoint struct {
	Size          Uint16
	Point         TpmsEccPoint
	refd4afd87    *C.TPM2B_ECC_POINT
	allocsd4afd87 interface{}
}

// TpmiAlgEccScheme type as declared in tss2/tss2_tpm2_types.h:1443
type TpmiAlgEccScheme uint16

// TpmiEccCurve type as declared in tss2/tss2_tpm2_types.h:1446
type TpmiEccCurve uint16

// TpmtEccScheme as declared in tss2/tss2_tpm2_types.h:1452
type TpmtEccScheme struct {
	Scheme         TpmiAlgEccScheme
	Details        TpmuAsymScheme
	refc97dbc77    *C.TPMT_ECC_SCHEME
	allocsc97dbc77 interface{}
}

// TpmsAlgorithmDetailEcc as declared in tss2/tss2_tpm2_types.h:1467
type TpmsAlgorithmDetailEcc struct {
	Curveid        Tpm2EccCurve
	Keysize        Uint16
	Kdf            TpmtKdfScheme
	Sign           TpmtEccScheme
	P              Tpm2bEccParameter
	A              Tpm2bEccParameter
	B              Tpm2bEccParameter
	Gx             Tpm2bEccParameter
	Gy             Tpm2bEccParameter
	N              Tpm2bEccParameter
	H              Tpm2bEccParameter
	ref9936fbe0    *C.TPMS_ALGORITHM_DETAIL_ECC
	allocs9936fbe0 interface{}
}

// TpmsSignatureRsa as declared in tss2/tss2_tpm2_types.h:1473
type TpmsSignatureRsa struct {
	Hash           TpmiAlgHash
	Sig            Tpm2bPublicKeyRsa
	refc969a88e    *C.TPMS_SIGNATURE_RSA
	allocsc969a88e interface{}
}

// TpmsSignatureRsassa as declared in tss2/tss2_tpm2_types.h:1476
type TpmsSignatureRsassa struct {
	Hash           TpmiAlgHash
	Sig            Tpm2bPublicKeyRsa
	refc969a88e    *C.TPMS_SIGNATURE_RSA
	allocsc969a88e interface{}
}

// TpmsSignatureRsapss as declared in tss2/tss2_tpm2_types.h:1477
type TpmsSignatureRsapss struct {
	Hash           TpmiAlgHash
	Sig            Tpm2bPublicKeyRsa
	refc969a88e    *C.TPMS_SIGNATURE_RSA
	allocsc969a88e interface{}
}

// TpmsSignatureEcc as declared in tss2/tss2_tpm2_types.h:1484
type TpmsSignatureEcc struct {
	Hash           TpmiAlgHash
	Signaturer     Tpm2bEccParameter
	Signatures     Tpm2bEccParameter
	ref74cc6e06    *C.TPMS_SIGNATURE_ECC
	allocs74cc6e06 interface{}
}

// TpmsSignatureEcdsa as declared in tss2/tss2_tpm2_types.h:1487
type TpmsSignatureEcdsa struct {
	Hash           TpmiAlgHash
	Signaturer     Tpm2bEccParameter
	Signatures     Tpm2bEccParameter
	ref74cc6e06    *C.TPMS_SIGNATURE_ECC
	allocs74cc6e06 interface{}
}

// TpmsSignatureEcdaa as declared in tss2/tss2_tpm2_types.h:1488
type TpmsSignatureEcdaa struct {
	Hash           TpmiAlgHash
	Signaturer     Tpm2bEccParameter
	Signatures     Tpm2bEccParameter
	ref74cc6e06    *C.TPMS_SIGNATURE_ECC
	allocs74cc6e06 interface{}
}

// TpmsSignatureSm2 as declared in tss2/tss2_tpm2_types.h:1489
type TpmsSignatureSm2 struct {
	Hash           TpmiAlgHash
	Signaturer     Tpm2bEccParameter
	Signatures     Tpm2bEccParameter
	ref74cc6e06    *C.TPMS_SIGNATURE_ECC
	allocs74cc6e06 interface{}
}

// TpmsSignatureEcschnorr as declared in tss2/tss2_tpm2_types.h:1490
type TpmsSignatureEcschnorr struct {
	Hash           TpmiAlgHash
	Signaturer     Tpm2bEccParameter
	Signatures     Tpm2bEccParameter
	ref74cc6e06    *C.TPMS_SIGNATURE_ECC
	allocs74cc6e06 interface{}
}

// TpmuSignature as declared in tss2/tss2_tpm2_types.h:1502
const sizeofTpmuSignature = unsafe.Sizeof(C.TPMU_SIGNATURE{})

type TpmuSignature [sizeofTpmuSignature]byte

// TpmtSignature as declared in tss2/tss2_tpm2_types.h:1508
type TpmtSignature struct {
	Sigalg         TpmiAlgSigScheme
	Signature      TpmuSignature
	refc461c44d    *C.TPMT_SIGNATURE
	allocsc461c44d interface{}
}

// TpmuEncryptedSecret as declared in tss2/tss2_tpm2_types.h:1516
const sizeofTpmuEncryptedSecret = unsafe.Sizeof(C.TPMU_ENCRYPTED_SECRET{})

type TpmuEncryptedSecret [sizeofTpmuEncryptedSecret]byte

// Tpm2bEncryptedSecret as declared in tss2/tss2_tpm2_types.h:1522
type Tpm2bEncryptedSecret struct {
	Size           Uint16
	Secret         [512]Byte
	ref66c6332e    *C.TPM2B_ENCRYPTED_SECRET
	allocs66c6332e interface{}
}

// TpmiAlgPublic type as declared in tss2/tss2_tpm2_types.h:1525
type TpmiAlgPublic uint16

// TpmuPublicId as declared in tss2/tss2_tpm2_types.h:1533
const sizeofTpmuPublicId = unsafe.Sizeof(C.TPMU_PUBLIC_ID{})

type TpmuPublicId [sizeofTpmuPublicId]byte

// TpmsKeyedhashParms as declared in tss2/tss2_tpm2_types.h:1538
type TpmsKeyedhashParms struct {
	Scheme         TpmtKeyedhashScheme
	ref9b28d654    *C.TPMS_KEYEDHASH_PARMS
	allocs9b28d654 interface{}
}

// TpmsAsymParms as declared in tss2/tss2_tpm2_types.h:1544
type TpmsAsymParms struct {
	Symmetric      TpmtSymDefObject
	Scheme         TpmtAsymScheme
	refc5c375f0    *C.TPMS_ASYM_PARMS
	allocsc5c375f0 interface{}
}

// TpmsRsaParms as declared in tss2/tss2_tpm2_types.h:1552
type TpmsRsaParms struct {
	Symmetric      TpmtSymDefObject
	Scheme         TpmtRsaScheme
	Keybits        TpmiRsaKeyBits
	Exponent       Uint32
	refba86b8bf    *C.TPMS_RSA_PARMS
	allocsba86b8bf interface{}
}

// TpmsEccParms as declared in tss2/tss2_tpm2_types.h:1560
type TpmsEccParms struct {
	Symmetric      TpmtSymDefObject
	Scheme         TpmtEccScheme
	Curveid        TpmiEccCurve
	Kdf            TpmtKdfScheme
	ref9903b705    *C.TPMS_ECC_PARMS
	allocs9903b705 interface{}
}

// TpmuPublicParms as declared in tss2/tss2_tpm2_types.h:1569
const sizeofTpmuPublicParms = unsafe.Sizeof(C.TPMU_PUBLIC_PARMS{})

type TpmuPublicParms [sizeofTpmuPublicParms]byte

// TpmtPublicParms as declared in tss2/tss2_tpm2_types.h:1575
type TpmtPublicParms struct {
	Type           TpmiAlgPublic
	Parameters     TpmuPublicParms
	reff4a57683    *C.TPMT_PUBLIC_PARMS
	allocsf4a57683 interface{}
}

// TpmtPublic as declared in tss2/tss2_tpm2_types.h:1585
type TpmtPublic struct {
	Type             TpmiAlgPublic
	Namealg          TpmiAlgHash
	Objectattributes TpmaObject
	Authpolicy       Tpm2bDigest
	Parameters       TpmuPublicParms
	Unique           TpmuPublicId
	ref4b565108      *C.TPMT_PUBLIC
	allocs4b565108   interface{}
}

// Tpm2bPublic as declared in tss2/tss2_tpm2_types.h:1591
type Tpm2bPublic struct {
	Size           Uint16
	Publicarea     TpmtPublic
	ref933e0a8a    *C.TPM2B_PUBLIC
	allocs933e0a8a interface{}
}

// Tpm2bTemplate as declared in tss2/tss2_tpm2_types.h:1597
type Tpm2bTemplate struct {
	Size           Uint16
	Buffer         [612]Byte
	ref3b894b6f    *C.TPM2B_TEMPLATE
	allocs3b894b6f interface{}
}

// Tpm2bPrivateVendorSpecific as declared in tss2/tss2_tpm2_types.h:1603
type Tpm2bPrivateVendorSpecific struct {
	Size          Uint16
	Buffer        [1280]Byte
	ref40be884    *C.TPM2B_PRIVATE_VENDOR_SPECIFIC
	allocs40be884 interface{}
}

// TpmuSensitiveComposite as declared in tss2/tss2_tpm2_types.h:1612
const sizeofTpmuSensitiveComposite = unsafe.Sizeof(C.TPMU_SENSITIVE_COMPOSITE{})

type TpmuSensitiveComposite [sizeofTpmuSensitiveComposite]byte

// TpmtSensitive as declared in tss2/tss2_tpm2_types.h:1620
type TpmtSensitive struct {
	Sensitivetype  TpmiAlgPublic
	Authvalue      Tpm2bAuth
	Seedvalue      Tpm2bDigest
	Sensitive      TpmuSensitiveComposite
	reff83e5145    *C.TPMT_SENSITIVE
	allocsf83e5145 interface{}
}

// Tpm2bSensitive as declared in tss2/tss2_tpm2_types.h:1626
type Tpm2bSensitive struct {
	Size          Uint16
	Sensitivearea TpmtSensitive
	refa9f386     *C.TPM2B_SENSITIVE
	allocsa9f386  interface{}
}

// Private as declared in tss2/tss2_tpm2_types.h:1633
type Private struct {
	Integrityouter Tpm2bDigest
	Integrityinner Tpm2bDigest
	Sensitive      Tpm2bSensitive
	ref990bdeb6    *C._PRIVATE
	allocs990bdeb6 interface{}
}

// Tpm2bPrivate as declared in tss2/tss2_tpm2_types.h:1639
type Tpm2bPrivate struct {
	Size           Uint16
	Buffer         [1550]Byte
	ref87ab6dda    *C.TPM2B_PRIVATE
	allocs87ab6dda interface{}
}

// TpmsIdObject as declared in tss2/tss2_tpm2_types.h:1645
type TpmsIdObject struct {
	Integrityhmac Tpm2bDigest
	Encidentity   Tpm2bDigest
	ref2f5f712    *C.TPMS_ID_OBJECT
	allocs2f5f712 interface{}
}

// Tpm2bIdObject as declared in tss2/tss2_tpm2_types.h:1651
type Tpm2bIdObject struct {
	Size           Uint16
	Credential     [132]Byte
	refd3594052    *C.TPM2B_ID_OBJECT
	allocsd3594052 interface{}
}

// Tpm2NvIndex type as declared in tss2/tss2_tpm2_types.h:1654
type Tpm2NvIndex uint32

// Tpm2Nt type as declared in tss2/tss2_tpm2_types.h:1662
type Tpm2Nt byte

// TpmsNvPinCounterParameters as declared in tss2/tss2_tpm2_types.h:1675
type TpmsNvPinCounterParameters struct {
	Pincount       Uint32
	Pinlimit       Uint32
	refcce8e2e8    *C.TPMS_NV_PIN_COUNTER_PARAMETERS
	allocscce8e2e8 interface{}
}

// TpmaNv type as declared in tss2/tss2_tpm2_types.h:1678
type TpmaNv uint32

// TpmsNvPublic as declared in tss2/tss2_tpm2_types.h:1713
type TpmsNvPublic struct {
	Nvindex        TpmiRhNvIndex
	Namealg        TpmiAlgHash
	Attributes     TpmaNv
	Authpolicy     Tpm2bDigest
	Datasize       Uint16
	refcb13297c    *C.TPMS_NV_PUBLIC
	allocscb13297c interface{}
}

// Tpm2bNvPublic as declared in tss2/tss2_tpm2_types.h:1719
type Tpm2bNvPublic struct {
	Size           Uint16
	Nvpublic       TpmsNvPublic
	ref1abf9e3c    *C.TPM2B_NV_PUBLIC
	allocs1abf9e3c interface{}
}

// Tpm2bContextSensitive as declared in tss2/tss2_tpm2_types.h:1725
type Tpm2bContextSensitive struct {
	Size           Uint16
	Buffer         [5120]Byte
	refbf0234fb    *C.TPM2B_CONTEXT_SENSITIVE
	allocsbf0234fb interface{}
}

// TpmsContextData as declared in tss2/tss2_tpm2_types.h:1731
type TpmsContextData struct {
	Integrity      Tpm2bDigest
	Encrypted      Tpm2bContextSensitive
	ref3075f0c5    *C.TPMS_CONTEXT_DATA
	allocs3075f0c5 interface{}
}

// Tpm2bContextData as declared in tss2/tss2_tpm2_types.h:1737
type Tpm2bContextData struct {
	Size           Uint16
	Buffer         [5188]Byte
	ref340baa68    *C.TPM2B_CONTEXT_DATA
	allocs340baa68 interface{}
}

// TpmsContext as declared in tss2/tss2_tpm2_types.h:1745
type TpmsContext struct {
	Sequence       Uint64
	Savedhandle    TpmiDhContext
	Hierarchy      TpmiRhHierarchy
	Contextblob    Tpm2bContextData
	refd0ffceeb    *C.TPMS_CONTEXT
	allocsd0ffceeb interface{}
}

// TpmsCreationData as declared in tss2/tss2_tpm2_types.h:1756
type TpmsCreationData struct {
	Pcrselect           TpmlPcrSelection
	Pcrdigest           Tpm2bDigest
	Locality            TpmaLocality
	Parentnamealg       Tpm2AlgId
	Parentname          Tpm2bName
	Parentqualifiedname Tpm2bName
	Outsideinfo         Tpm2bData
	refe3b9531d         *C.TPMS_CREATION_DATA
	allocse3b9531d      interface{}
}

// Tpm2bCreationData as declared in tss2/tss2_tpm2_types.h:1762
type Tpm2bCreationData struct {
	Size           Uint16
	Creationdata   TpmsCreationData
	ref4bdaf212    *C.TPM2B_CREATION_DATA
	allocs4bdaf212 interface{}
}

// TpmAt type as declared in tss2/tss2_tpm2_types.h:1764
type TpmAt uint32

// TpmEa type as declared in tss2/tss2_tpm2_types.h:1773
type TpmEa uint32

// TpmiRhAc type as declared in tss2/tss2_tpm2_types.h:1777
type TpmiRhAc uint32

// TpmsAcOutput as declared in tss2/tss2_tpm2_types.h:1783
type TpmsAcOutput struct {
	Tag            TpmAt
	Data           Uint32
	refd79be361    *C.TPMS_AC_OUTPUT
	allocsd79be361 interface{}
}

// TpmlAcCapabilities as declared in tss2/tss2_tpm2_types.h:1789
type TpmlAcCapabilities struct {
	Count          Uint32
	Accapabilities [128]TpmsAcOutput
	ref9e7983cc    *C.TPML_AC_CAPABILITIES
	allocs9e7983cc interface{}
}

// Tss2SysContext as declared in tss2/tss2_sys.h:26
type Tss2SysContext C.TSS2_SYS_CONTEXT

// Tss2lSysAuthCommand as declared in tss2/tss2_sys.h:34
type Tss2lSysAuthCommand struct {
	Count          Uint16T
	Auths          [3]TpmsAuthCommand
	reff9bbf97f    *C.TSS2L_SYS_AUTH_COMMAND
	allocsf9bbf97f interface{}
}

// Tss2lSysAuthResponse as declared in tss2/tss2_sys.h:39
type Tss2lSysAuthResponse struct {
	Count          Uint16T
	Auths          [3]TpmsAuthResponse
	ref44662040    *C.TSS2L_SYS_AUTH_RESPONSE
	allocs44662040 interface{}
}

// FapiContext as declared in tss2/tss2_fapi.h:17
type FapiContext C.FAPI_CONTEXT

// FapiPollHandle type as declared in tss2/tss2_fapi.h:53
type FapiPollHandle [0]byte

// FapiCbAuth type as declared in tss2/tss2_fapi.h:655
type FapiCbAuth func(context *FapiContext, description []string, auth [][]byte, userdata unsafe.Pointer) Tss2Rc

// FapiCbBranch type as declared in tss2/tss2_fapi.h:666
type FapiCbBranch func(context *FapiContext, description []string, branchnames [][]string, numbranches SizeT, selectedbranch []SizeT, userdata unsafe.Pointer) Tss2Rc

// FapiCbSign type as declared in tss2/tss2_fapi.h:679
type FapiCbSign func(context *FapiContext, description []string, publickey []string, publickeyhint []string, hashalg Uint32T, datatosign []Uint8T, datatosignsize SizeT, signature [][]Uint8T, signaturesize []SizeT, userdata unsafe.Pointer) Tss2Rc

// FapiCbPolicyaction type as declared in tss2/tss2_fapi.h:696
type FapiCbPolicyaction func(context *FapiContext, action []string, userdata unsafe.Pointer) Tss2Rc

// DivT as declared in include/stdlib.h:62
type DivT struct {
	Quot           int32
	Rem            int32
	refd6897e45    *C.div_t
	allocsd6897e45 interface{}
}

// LdivT as declared in include/stdlib.h:70
type LdivT struct {
	Quot           int32
	Rem            int32
	refde5fe7da    *C.ldiv_t
	allocsde5fe7da interface{}
}

// LldivT as declared in include/stdlib.h:80
type LldivT struct {
	Quot           int64
	Rem            int64
	refbee7bf96    *C.lldiv_t
	allocsbee7bf96 interface{}
}

// _ComparFnT type as declared in include/stdlib.h:808
type _ComparFnT func(arg0 unsafe.Pointer, arg1 unsafe.Pointer) int32

// Float32 type as declared in bits/floatn-common.h:214
type Float32 float32

// Float64 type as declared in bits/floatn-common.h:251
type Float64 float64

// Float32x type as declared in bits/floatn-common.h:268
type Float32x float64

// Float64x type as declared in bits/floatn-common.h:285
type Float64x float64

// UChar type as declared in sys/types.h:33
type UChar byte

// UShort type as declared in sys/types.h:34
type UShort uint16

// UInt type as declared in sys/types.h:35
type UInt uint32

// ULong type as declared in sys/types.h:36
type ULong uint32

// QuadT type as declared in sys/types.h:37
type QuadT int32

// UQuadT type as declared in sys/types.h:38
type UQuadT uint32

// FsidT as declared in sys/types.h:39
type FsidT struct {
	_Val           [2]int32
	ref3fddfece    *C.__fsid_t
	allocs3fddfece interface{}
}

// LoffT type as declared in sys/types.h:42
type LoffT int32

// InoT type as declared in sys/types.h:47
type InoT uint32

// DevT type as declared in sys/types.h:59
type DevT uint32

// GidT type as declared in sys/types.h:64
type GidT uint32

// ModeT type as declared in sys/types.h:69
type ModeT uint32

// NlinkT type as declared in sys/types.h:74
type NlinkT uint32

// UidT type as declared in sys/types.h:79
type UidT uint32

// OffT type as declared in sys/types.h:85
type OffT int32

// PidT type as declared in sys/types.h:97
type PidT int32

// IdT type as declared in sys/types.h:103
type IdT uint32

// SsizeT type as declared in sys/types.h:108
type SsizeT int32

// DaddrT type as declared in sys/types.h:114
type DaddrT int32

// CaddrT type as declared in sys/types.h:115
type CaddrT []byte

// KeyT type as declared in sys/types.h:121
type KeyT int32

// Ulong type as declared in sys/types.h:148
type Ulong uint32

// Ushort type as declared in sys/types.h:149
type Ushort uint16

// Uint type as declared in sys/types.h:150
type Uint uint32

// UInt8T type as declared in sys/types.h:158
type UInt8T byte

// UInt16T type as declared in sys/types.h:159
type UInt16T uint16

// UInt32T type as declared in sys/types.h:160
type UInt32T uint32

// UInt64T type as declared in sys/types.h:161
type UInt64T uint32

// RegisterT type as declared in sys/types.h:166
type RegisterT int32

// BlksizeT type as declared in sys/types.h:185
type BlksizeT int32

// BlkcntT type as declared in sys/types.h:192
type BlkcntT int32

// FsblkcntT type as declared in sys/types.h:196
type FsblkcntT uint32

// FsfilcntT type as declared in sys/types.h:200
type FsfilcntT uint32

// ClockT type as declared in types/clock_t.h:7
type ClockT int32

// ClockidT type as declared in types/clockid_t.h:7
type ClockidT int32

// TimeT type as declared in types/time_t.h:7
type TimeT int32

// TimerT type as declared in types/timer_t.h:7
type TimerT unsafe.Pointer

// SusecondsT type as declared in sys/select.h:43
type SusecondsT int32

// _FdMask type as declared in sys/select.h:49
type _FdMask int32

// FdSet as declared in sys/select.h:70
type FdSet struct {
	_FdsBits       [16]_FdMask
	ref89e67f53    *C.fd_set
	allocs89e67f53 interface{}
}

// FdMask type as declared in sys/select.h:77
type FdMask int32

// SigsetT as declared in types/sigset_t.h:7
type SigsetT struct {
	_Val           [16]uint32
	refa44732af    *C.__sigset_t
	allocsa44732af interface{}
}

// _SigsetT as declared in types/__sigset_t.h:8
type _SigsetT struct {
	_Val           [16]uint32
	refa44732af    *C.__sigset_t
	allocsa44732af interface{}
}

// PthreadT type as declared in bits/pthreadtypes.h:27
type PthreadT uint32

// PthreadMutexattrT as declared in bits/pthreadtypes.h:36
const sizeofPthreadMutexattrT = unsafe.Sizeof(C.pthread_mutexattr_t{})

type PthreadMutexattrT [sizeofPthreadMutexattrT]byte

// PthreadCondattrT as declared in bits/pthreadtypes.h:45
const sizeofPthreadCondattrT = unsafe.Sizeof(C.pthread_condattr_t{})

type PthreadCondattrT [sizeofPthreadCondattrT]byte

// PthreadKeyT type as declared in bits/pthreadtypes.h:49
type PthreadKeyT uint32

// PthreadOnceT type as declared in bits/pthreadtypes.h:53
type PthreadOnceT int32

// PthreadAttrT as declared in bits/pthreadtypes.h:62
const sizeofPthreadAttrT = unsafe.Sizeof(C.pthread_attr_t{})

type PthreadAttrT [sizeofPthreadAttrT]byte

// PthreadMutexT as declared in bits/pthreadtypes.h:72
const sizeofPthreadMutexT = unsafe.Sizeof(C.pthread_mutex_t{})

type PthreadMutexT [sizeofPthreadMutexT]byte

// PthreadCondT as declared in bits/pthreadtypes.h:80
const sizeofPthreadCondT = unsafe.Sizeof(C.pthread_cond_t{})

type PthreadCondT [sizeofPthreadCondT]byte

// PthreadRwlockT as declared in bits/pthreadtypes.h:91
const sizeofPthreadRwlockT = unsafe.Sizeof(C.pthread_rwlock_t{})

type PthreadRwlockT [sizeofPthreadRwlockT]byte

// PthreadRwlockattrT as declared in bits/pthreadtypes.h:97
const sizeofPthreadRwlockattrT = unsafe.Sizeof(C.pthread_rwlockattr_t{})

type PthreadRwlockattrT [sizeofPthreadRwlockattrT]byte

// PthreadSpinlockT type as declared in bits/pthreadtypes.h:103
type PthreadSpinlockT int32

// PthreadBarrierT as declared in bits/pthreadtypes.h:112
const sizeofPthreadBarrierT = unsafe.Sizeof(C.pthread_barrier_t{})

type PthreadBarrierT [sizeofPthreadBarrierT]byte

// PthreadBarrierattrT as declared in bits/pthreadtypes.h:118
const sizeofPthreadBarrierattrT = unsafe.Sizeof(C.pthread_barrierattr_t{})

type PthreadBarrierattrT [sizeofPthreadBarrierattrT]byte

// _PthreadListT as declared in bits/thread-shared-types.h:53
type _PthreadListT struct {
	_Prev          []_PthreadInternalList
	_Next          []_PthreadInternalList
	ref3eec1ba6    *C.__pthread_list_t
	allocs3eec1ba6 interface{}
}

// _PthreadSlistT as declared in bits/thread-shared-types.h:58
type _PthreadSlistT struct {
	_Next          []_PthreadInternalSlist
	ref8e552e08    *C.__pthread_slist_t
	allocs8e552e08 interface{}
}

// Tss2RcHandler type as declared in tss2/tss2_rc.h:14
type Tss2RcHandler func(rc Tss2Rc) *string

// _GwcharT type as declared in include/inttypes.h:34
type _GwcharT int32

// ImaxdivT as declared in include/inttypes.h:275
type ImaxdivT struct {
	Quot           int32
	Rem            int32
	ref873cd79e    *C.imaxdiv_t
	allocs873cd79e interface{}
}

// _PthreadMutexS as declared in bits/struct_mutex.h:22
type _PthreadMutexS struct {
	_Lock          int32
	_Count         uint32
	_Owner         int32
	_Nusers        uint32
	_Kind          int32
	_Spins         int16
	_Elision       int16
	_List          _PthreadListT
	ref58941059    *C.struct___pthread_mutex_s
	allocs58941059 interface{}
}

// _PthreadRwlockArchT as declared in bits/struct_rwlock.h:23
type _PthreadRwlockArchT struct {
	_Readers       uint32
	_Writers       uint32
	_WrphaseFutex  uint32
	_WritersFutex  uint32
	_Pad3          uint32
	_Pad4          uint32
	_CurWriter     int32
	_Shared        int32
	_Rwelision     int8
	_Pad1          [7]byte
	_Pad2          uint32
	_Flags         uint32
	refb4dcb58a    *C.struct___pthread_rwlock_arch_t
	allocsb4dcb58a interface{}
}

// Drand48Data as declared in include/stdlib.h:490
type Drand48Data struct {
	_X             [3]uint16
	_OldX          [3]uint16
	_C             uint16
	_Init          uint16
	_A             uint64
	ref34d792ac    *C.struct_drand48_data
	allocs34d792ac interface{}
}

// RandomData as declared in include/stdlib.h:423
type RandomData struct {
	Fptr          []Int32T
	Rptr          []Int32T
	State         []Int32T
	RandType      int32
	RandDeg       int32
	RandSep       int32
	EndPtr        []Int32T
	refb9fde78    *C.struct_random_data
	allocsb9fde78 interface{}
}

// Timespec as declared in types/struct_timespec.h:10
type Timespec struct {
	TvSec          _TimeT
	TvNsec         _SyscallSlongT
	refd3d35df8    *C.struct_timespec
	allocsd3d35df8 interface{}
}

// Timeval as declared in types/struct_timeval.h:8
type Timeval struct {
	TvSec          _TimeT
	TvUsec         _SusecondsT
	ref260d2a7d    *C.struct_timeval
	allocs260d2a7d interface{}
}
