// License: CC-0

// WARNING: This file has automatically been generated on Sat, 17 Apr 2021 22:05:09 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package go_tpm2_tss

/*
#cgo pkg-config: tss2-tcti-mssim tss2-tcti-device tss2-mu tss2-tctildr tss2-rc tss2-sys tss2-esys
#cgo CFLAGS: -I ../c/include
#include "tss2/tss2_common.h"
#include "tss2/tss2_esys.h"
#include "tss2/tss2_mu.h"
#include "tss2/tss2_rc.h"
#include "tss2/tss2_sys.h"
#include "tss2/tss2_tcti_device.h"
#include "tss2/tss2_tcti.h"
#include "tss2/tss2_tctildr.h"
#include "tss2/tss2_tcti_mssim.h"
#include "tss2/tss2_tcti_tbs.h"
#include "tss2/tss2_tpm2_types.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Uint8 type as declared in tss2/tss2_common.h:18
type Uint8 byte

// Byte type as declared in tss2/tss2_common.h:19
type Byte byte

// Int8 type as declared in tss2/tss2_common.h:20
type Int8 int8

// Bool type as declared in tss2/tss2_common.h:21
type Bool int32

// Uint16 type as declared in tss2/tss2_common.h:22
type Uint16 uint16

// Int16 type as declared in tss2/tss2_common.h:23
type Int16 int16

// Uint32 type as declared in tss2/tss2_common.h:24
type Uint32 uint32

// Int32 type as declared in tss2/tss2_common.h:25
type Int32 int32

// Uint64 type as declared in tss2/tss2_common.h:26
type Uint64 uint32

// Int64 type as declared in tss2/tss2_common.h:27
type Int64 int32

// Tss2AbiVersion as declared in tss2/tss2_common.h:37
type Tss2AbiVersion struct {
	Tsscreator     Uint32T
	Tssfamily      Uint32T
	Tsslevel       Uint32T
	Tssversion     Uint32T
	ref731c8581    *C.TSS2_ABI_VERSION
	allocs731c8581 interface{}
}

// Tss2Rc type as declared in tss2/tss2_common.h:45
type Tss2Rc uint32

// IntLeast8T type as declared in include/stdint.h:43
type IntLeast8T int8

// IntLeast16T type as declared in include/stdint.h:44
type IntLeast16T int16

// IntLeast32T type as declared in include/stdint.h:45
type IntLeast32T int32

// IntLeast64T type as declared in include/stdint.h:46
type IntLeast64T int32

// UintLeast8T type as declared in include/stdint.h:49
type UintLeast8T byte

// UintLeast16T type as declared in include/stdint.h:50
type UintLeast16T uint16

// UintLeast32T type as declared in include/stdint.h:51
type UintLeast32T uint32

// UintLeast64T type as declared in include/stdint.h:52
type UintLeast64T uint32

// IntFast8T type as declared in include/stdint.h:58
type IntFast8T int8

// IntFast16T type as declared in include/stdint.h:60
type IntFast16T int32

// IntFast32T type as declared in include/stdint.h:61
type IntFast32T int32

// IntFast64T type as declared in include/stdint.h:62
type IntFast64T int32

// UintFast8T type as declared in include/stdint.h:71
type UintFast8T byte

// UintFast16T type as declared in include/stdint.h:73
type UintFast16T uint32

// UintFast32T type as declared in include/stdint.h:74
type UintFast32T uint32

// UintFast64T type as declared in include/stdint.h:75
type UintFast64T uint32

// IntptrT type as declared in include/stdint.h:87
type IntptrT int32

// UintptrT type as declared in include/stdint.h:90
type UintptrT uint32

// IntmaxT type as declared in include/stdint.h:101
type IntmaxT int32

// UintmaxT type as declared in include/stdint.h:102
type UintmaxT uint32

// Int8T type as declared in bits/stdint-intn.h:24
type Int8T int8

// Int16T type as declared in bits/stdint-intn.h:25
type Int16T int16

// Int32T type as declared in bits/stdint-intn.h:26
type Int32T int32

// Int64T type as declared in bits/stdint-intn.h:27
type Int64T int32

// Uint8T type as declared in bits/stdint-uintn.h:24
type Uint8T byte

// Uint16T type as declared in bits/stdint-uintn.h:25
type Uint16T uint16

// Uint32T type as declared in bits/stdint-uintn.h:26
type Uint32T uint32

// Uint64T type as declared in bits/stdint-uintn.h:27
type Uint64T uint32

// EsysTr type as declared in tss2/tss2_esys.h:16
type EsysTr uint32

// EsysContext as declared in tss2/tss2_esys.h:66
type EsysContext C.ESYS_CONTEXT

// Tss2TctiPollHandle type as declared in tss2/tss2_tcti.h:57
type Tss2TctiPollHandle [0]byte

// Tss2TctiContext as declared in tss2/tss2_tcti.h:140
type Tss2TctiContext C.TSS2_TCTI_CONTEXT

// Tss2TctiTransmitFcn type as declared in tss2/tss2_tcti.h:146
type Tss2TctiTransmitFcn func(tcticontext *Tss2TctiContext, size SizeT, command *Uint8T) Tss2Rc

// Tss2TctiReceiveFcn type as declared in tss2/tss2_tcti.h:150
type Tss2TctiReceiveFcn func(tcticontext *Tss2TctiContext, size []SizeT, response *Uint8T, timeout Int32T) Tss2Rc

// Tss2TctiFinalizeFcn type as declared in tss2/tss2_tcti.h:155
type Tss2TctiFinalizeFcn func(tcticontext *Tss2TctiContext)

// Tss2TctiCancelFcn type as declared in tss2/tss2_tcti.h:157
type Tss2TctiCancelFcn func(tcticontext *Tss2TctiContext) Tss2Rc

// Tss2TctiGetPollHandlesFcn type as declared in tss2/tss2_tcti.h:159
type Tss2TctiGetPollHandlesFcn func(tcticontext *Tss2TctiContext, handles *Tss2TctiPollHandle, numHandles *SizeT) Tss2Rc

// Tss2TctiSetLocalityFcn type as declared in tss2/tss2_tcti.h:163
type Tss2TctiSetLocalityFcn func(tcticontext *Tss2TctiContext, locality Uint8T) Tss2Rc

// Tss2TctiMakeStickyFcn type as declared in tss2/tss2_tcti.h:166
type Tss2TctiMakeStickyFcn func(tcticontext *Tss2TctiContext, handle []Tpm2Handle, sticky Uint8T) Tss2Rc

// Tss2TctiInitFunc type as declared in tss2/tss2_tcti.h:170
type Tss2TctiInitFunc func(tcticontext *Tss2TctiContext, size []uint32, config string) uint32

// Tss2TctiContextCommonV1 as declared in tss2/tss2_tcti.h:185
type Tss2TctiContextCommonV1 struct {
	Magic          Uint64T
	Version        Uint32T
	Transmit       Tss2TctiTransmitFcn
	Receive        Tss2TctiReceiveFcn
	Finalize       Tss2TctiFinalizeFcn
	Cancel         Tss2TctiCancelFcn
	Getpollhandles Tss2TctiGetPollHandlesFcn
	Setlocality    Tss2TctiSetLocalityFcn
	ref6a31a31a    *C.TSS2_TCTI_CONTEXT_COMMON_V1
	allocs6a31a31a interface{}
}

// Tss2TctiContextCommonV2 as declared in tss2/tss2_tcti.h:190
type Tss2TctiContextCommonV2 struct {
	V1             Tss2TctiContextCommonV1
	Makesticky     Tss2TctiMakeStickyFcn
	reff338f2a0    *C.TSS2_TCTI_CONTEXT_COMMON_V2
	allocsf338f2a0 interface{}
}

// Tss2TctiContextCommonCurrent as declared in tss2/tss2_tcti.h:192
type Tss2TctiContextCommonCurrent struct {
	V1             Tss2TctiContextCommonV1
	Makesticky     Tss2TctiMakeStickyFcn
	reff338f2a0    *C.TSS2_TCTI_CONTEXT_COMMON_V2
	allocsf338f2a0 interface{}
}

// Tss2TctiInfo as declared in tss2/tss2_tcti.h:202
type Tss2TctiInfo C.TSS2_TCTI_INFO

// Tss2TctiInfoFunc type as declared in tss2/tss2_tcti.h:204
type Tss2TctiInfoFunc func() *Tss2TctiInfo

// PtrdiffT type as declared in include/stddef.h:143
type PtrdiffT int32

// SizeT type as declared in include/stddef.h:209
type SizeT uint32

// WcharT type as declared in include/stddef.h:321
type WcharT int32

// Tpm2AlgId type as declared in tss2/tss2_tpm2_types.h:70
type Tpm2AlgId uint16

// Tpm2EccCurve type as declared in tss2/tss2_tpm2_types.h:116
type Tpm2EccCurve uint16

// Tpm2Cc type as declared in tss2/tss2_tpm2_types.h:128
type Tpm2Cc uint32

// Tpm2AlgorithmId type as declared in tss2/tss2_tpm2_types.h:249
type Tpm2AlgorithmId uint32

// Tpm2ModifierIndicator type as declared in tss2/tss2_tpm2_types.h:250
type Tpm2ModifierIndicator uint32

// Tpm2AuthorizationSize type as declared in tss2/tss2_tpm2_types.h:251
type Tpm2AuthorizationSize uint32

// Tpm2ParameterSize type as declared in tss2/tss2_tpm2_types.h:252
type Tpm2ParameterSize uint32

// Tpm2KeySize type as declared in tss2/tss2_tpm2_types.h:253
type Tpm2KeySize uint16

// Tpm2KeyBits type as declared in tss2/tss2_tpm2_types.h:254
type Tpm2KeyBits uint16

// Tpm2Spec type as declared in tss2/tss2_tpm2_types.h:257
type Tpm2Spec uint32

// Tpm2Generated type as declared in tss2/tss2_tpm2_types.h:265
type Tpm2Generated uint32

// Tpm2Rc type as declared in tss2/tss2_tpm2_types.h:269
type Tpm2Rc uint32

// Tpm2ClockAdjust type as declared in tss2/tss2_tpm2_types.h:393
type Tpm2ClockAdjust int8

// Tpm2Eo type as declared in tss2/tss2_tpm2_types.h:403
type Tpm2Eo uint16

// Tpm2St type as declared in tss2/tss2_tpm2_types.h:418
type Tpm2St uint16

// Tpm2Su type as declared in tss2/tss2_tpm2_types.h:441
type Tpm2Su uint16

// Tpm2Se type as declared in tss2/tss2_tpm2_types.h:446
type Tpm2Se byte

// Tpm2Cap type as declared in tss2/tss2_tpm2_types.h:452
type Tpm2Cap uint32

// Tpm2Pt type as declared in tss2/tss2_tpm2_types.h:467
type Tpm2Pt uint32

// Tpm2PtPcr type as declared in tss2/tss2_tpm2_types.h:540
type Tpm2PtPcr uint32

// Tpm2Ps type as declared in tss2/tss2_tpm2_types.h:574
type Tpm2Ps uint32

// Tpm2Handle type as declared in tss2/tss2_tpm2_types.h:593
type Tpm2Handle uint32

// Tpm2Ht type as declared in tss2/tss2_tpm2_types.h:596
type Tpm2Ht byte

// Tpm2Rh type as declared in tss2/tss2_tpm2_types.h:608
type Tpm2Rh uint32

// Tpm2Hc type as declared in tss2/tss2_tpm2_types.h:629
type Tpm2Hc uint32

// TpmaAlgorithm type as declared in tss2/tss2_tpm2_types.h:661
type TpmaAlgorithm uint32

// TpmaObject type as declared in tss2/tss2_tpm2_types.h:674
type TpmaObject uint32

// TpmaSession type as declared in tss2/tss2_tpm2_types.h:694
type TpmaSession byte

// TpmaLocality type as declared in tss2/tss2_tpm2_types.h:705
type TpmaLocality byte

// TpmaPermanent type as declared in tss2/tss2_tpm2_types.h:716
type TpmaPermanent uint32

// TpmaStartupClear type as declared in tss2/tss2_tpm2_types.h:728
type TpmaStartupClear uint32

// TpmaMemory type as declared in tss2/tss2_tpm2_types.h:738
type TpmaMemory uint32

// TpmaCc type as declared in tss2/tss2_tpm2_types.h:746
type TpmaCc uint32

// TpmaModes type as declared in tss2/tss2_tpm2_types.h:762
type TpmaModes uint32

// TpmiYesNo type as declared in tss2/tss2_tpm2_types.h:768
type TpmiYesNo byte

// TpmiDhObject type as declared in tss2/tss2_tpm2_types.h:773
type TpmiDhObject uint32

// TpmiDhPersistent type as declared in tss2/tss2_tpm2_types.h:776
type TpmiDhPersistent uint32

// TpmiDhEntity type as declared in tss2/tss2_tpm2_types.h:779
type TpmiDhEntity uint32

// TpmiDhPcr type as declared in tss2/tss2_tpm2_types.h:782
type TpmiDhPcr uint32

// TpmiShAuthSession type as declared in tss2/tss2_tpm2_types.h:785
type TpmiShAuthSession uint32

// TpmiShHmac type as declared in tss2/tss2_tpm2_types.h:788
type TpmiShHmac uint32

// TpmiShPolicy type as declared in tss2/tss2_tpm2_types.h:791
type TpmiShPolicy uint32

// TpmiDhContext type as declared in tss2/tss2_tpm2_types.h:794
type TpmiDhContext uint32

// TpmiRhHierarchy type as declared in tss2/tss2_tpm2_types.h:797
type TpmiRhHierarchy uint32

// TpmiRhEnables type as declared in tss2/tss2_tpm2_types.h:800
type TpmiRhEnables uint32

// TpmiRhHierarchyAuth type as declared in tss2/tss2_tpm2_types.h:803
type TpmiRhHierarchyAuth uint32

// TpmiRhPlatform type as declared in tss2/tss2_tpm2_types.h:806
type TpmiRhPlatform uint32

// TpmiRhOwner type as declared in tss2/tss2_tpm2_types.h:809
type TpmiRhOwner uint32

// TpmiRhEndorsement type as declared in tss2/tss2_tpm2_types.h:812
type TpmiRhEndorsement uint32

// TpmiRhProvision type as declared in tss2/tss2_tpm2_types.h:815
type TpmiRhProvision uint32

// TpmiRhClear type as declared in tss2/tss2_tpm2_types.h:818
type TpmiRhClear uint32

// TpmiRhNvAuth type as declared in tss2/tss2_tpm2_types.h:821
type TpmiRhNvAuth uint32

// TpmiRhLockout type as declared in tss2/tss2_tpm2_types.h:824
type TpmiRhLockout uint32

// TpmiRhNvIndex type as declared in tss2/tss2_tpm2_types.h:827
type TpmiRhNvIndex uint32

// TpmiAlgHash type as declared in tss2/tss2_tpm2_types.h:830
type TpmiAlgHash uint16

// TpmiAlgAsym type as declared in tss2/tss2_tpm2_types.h:833
type TpmiAlgAsym uint16

// TpmiAlgSym type as declared in tss2/tss2_tpm2_types.h:836
type TpmiAlgSym uint16

// TpmiAlgSymObject type as declared in tss2/tss2_tpm2_types.h:839
type TpmiAlgSymObject uint16

// TpmiAlgSymMode type as declared in tss2/tss2_tpm2_types.h:842
type TpmiAlgSymMode uint16

// TpmiAlgKdf type as declared in tss2/tss2_tpm2_types.h:845
type TpmiAlgKdf uint16

// TpmiAlgSigScheme type as declared in tss2/tss2_tpm2_types.h:848
type TpmiAlgSigScheme uint16

// TpmiEccKeyExchange type as declared in tss2/tss2_tpm2_types.h:851
type TpmiEccKeyExchange uint16

// TpmiStCommandTag type as declared in tss2/tss2_tpm2_types.h:854
type TpmiStCommandTag uint16

// TpmsEmpty as declared in tss2/tss2_tpm2_types.h:859
type TpmsEmpty C.TPMS_EMPTY

// TpmsAlgorithmDescription as declared in tss2/tss2_tpm2_types.h:865
type TpmsAlgorithmDescription C.TPMS_ALGORITHM_DESCRIPTION

// TpmuHa as declared in tss2/tss2_tpm2_types.h:874
const sizeofTpmuHa = unsafe.Sizeof(C.TPMU_HA{})

type TpmuHa [sizeofTpmuHa]byte

// TpmtHa as declared in tss2/tss2_tpm2_types.h:880
type TpmtHa C.TPMT_HA

// Tpm2bDigest as declared in tss2/tss2_tpm2_types.h:886
type Tpm2bDigest C.TPM2B_DIGEST

// Tpm2bData as declared in tss2/tss2_tpm2_types.h:892
type Tpm2bData C.TPM2B_DATA

// Tpm2bNonce as declared in tss2/tss2_tpm2_types.h:895
type Tpm2bNonce C.TPM2B_DIGEST

// Tpm2bAuth as declared in tss2/tss2_tpm2_types.h:898
type Tpm2bAuth C.TPM2B_DIGEST

// Tpm2bOperand as declared in tss2/tss2_tpm2_types.h:901
type Tpm2bOperand C.TPM2B_DIGEST

// Tpm2bEvent as declared in tss2/tss2_tpm2_types.h:907
type Tpm2bEvent C.TPM2B_EVENT

// Tpm2bMaxBuffer as declared in tss2/tss2_tpm2_types.h:913
type Tpm2bMaxBuffer C.TPM2B_MAX_BUFFER

// Tpm2bMaxNvBuffer as declared in tss2/tss2_tpm2_types.h:919
type Tpm2bMaxNvBuffer C.TPM2B_MAX_NV_BUFFER

// Tpm2bTimeout as declared in tss2/tss2_tpm2_types.h:922
type Tpm2bTimeout C.TPM2B_DIGEST

// Tpm2bIv as declared in tss2/tss2_tpm2_types.h:928
type Tpm2bIv C.TPM2B_IV

// TpmuName as declared in tss2/tss2_tpm2_types.h:934
const sizeofTpmuName = unsafe.Sizeof(C.TPMU_NAME{})

type TpmuName [sizeofTpmuName]byte

// Tpm2bName as declared in tss2/tss2_tpm2_types.h:940
type Tpm2bName C.TPM2B_NAME

// TpmsPcrSelect as declared in tss2/tss2_tpm2_types.h:946
type TpmsPcrSelect C.TPMS_PCR_SELECT

// TpmsPcrSelection as declared in tss2/tss2_tpm2_types.h:953
type TpmsPcrSelection C.TPMS_PCR_SELECTION

// TpmtTkCreation as declared in tss2/tss2_tpm2_types.h:960
type TpmtTkCreation C.TPMT_TK_CREATION

// TpmtTkVerified as declared in tss2/tss2_tpm2_types.h:967
type TpmtTkVerified C.TPMT_TK_VERIFIED

// TpmtTkAuth as declared in tss2/tss2_tpm2_types.h:974
type TpmtTkAuth C.TPMT_TK_AUTH

// TpmtTkHashcheck as declared in tss2/tss2_tpm2_types.h:981
type TpmtTkHashcheck C.TPMT_TK_HASHCHECK

// TpmsAlgProperty as declared in tss2/tss2_tpm2_types.h:987
type TpmsAlgProperty C.TPMS_ALG_PROPERTY

// TpmsTaggedProperty as declared in tss2/tss2_tpm2_types.h:993
type TpmsTaggedProperty C.TPMS_TAGGED_PROPERTY

// TpmsTaggedPcrSelect as declared in tss2/tss2_tpm2_types.h:1000
type TpmsTaggedPcrSelect C.TPMS_TAGGED_PCR_SELECT

// TpmsTaggedPolicy as declared in tss2/tss2_tpm2_types.h:1006
type TpmsTaggedPolicy C.TPMS_TAGGED_POLICY

// TpmlCc as declared in tss2/tss2_tpm2_types.h:1012
type TpmlCc C.TPML_CC

// TpmlCca as declared in tss2/tss2_tpm2_types.h:1018
type TpmlCca C.TPML_CCA

// TpmlAlg as declared in tss2/tss2_tpm2_types.h:1024
type TpmlAlg C.TPML_ALG

// TpmlHandle as declared in tss2/tss2_tpm2_types.h:1030
type TpmlHandle C.TPML_HANDLE

// TpmlDigest as declared in tss2/tss2_tpm2_types.h:1036
type TpmlDigest C.TPML_DIGEST

// TpmlDigestValues as declared in tss2/tss2_tpm2_types.h:1042
type TpmlDigestValues C.TPML_DIGEST_VALUES

// TpmlPcrSelection as declared in tss2/tss2_tpm2_types.h:1048
type TpmlPcrSelection C.TPML_PCR_SELECTION

// TpmlAlgProperty as declared in tss2/tss2_tpm2_types.h:1054
type TpmlAlgProperty C.TPML_ALG_PROPERTY

// TpmlTaggedTpmProperty as declared in tss2/tss2_tpm2_types.h:1060
type TpmlTaggedTpmProperty C.TPML_TAGGED_TPM_PROPERTY

// TpmlTaggedPcrProperty as declared in tss2/tss2_tpm2_types.h:1066
type TpmlTaggedPcrProperty C.TPML_TAGGED_PCR_PROPERTY

// TpmlEccCurve as declared in tss2/tss2_tpm2_types.h:1072
type TpmlEccCurve C.TPML_ECC_CURVE

// TpmlIntelPttProperty as declared in tss2/tss2_tpm2_types.h:1078
type TpmlIntelPttProperty C.TPML_INTEL_PTT_PROPERTY

// TpmuCapabilities as declared in tss2/tss2_tpm2_types.h:1092
const sizeofTpmuCapabilities = unsafe.Sizeof(C.TPMU_CAPABILITIES{})

type TpmuCapabilities [sizeofTpmuCapabilities]byte

// TpmsCapabilityData as declared in tss2/tss2_tpm2_types.h:1098
type TpmsCapabilityData C.TPMS_CAPABILITY_DATA

// TpmsClockInfo as declared in tss2/tss2_tpm2_types.h:1106
type TpmsClockInfo C.TPMS_CLOCK_INFO

// TpmsTimeInfo as declared in tss2/tss2_tpm2_types.h:1112
type TpmsTimeInfo C.TPMS_TIME_INFO

// TpmsTimeAttestInfo as declared in tss2/tss2_tpm2_types.h:1118
type TpmsTimeAttestInfo C.TPMS_TIME_ATTEST_INFO

// TpmsCertifyInfo as declared in tss2/tss2_tpm2_types.h:1124
type TpmsCertifyInfo C.TPMS_CERTIFY_INFO

// TpmsQuoteInfo as declared in tss2/tss2_tpm2_types.h:1130
type TpmsQuoteInfo C.TPMS_QUOTE_INFO

// TpmsCommandAuditInfo as declared in tss2/tss2_tpm2_types.h:1138
type TpmsCommandAuditInfo C.TPMS_COMMAND_AUDIT_INFO

// TpmsSessionAuditInfo as declared in tss2/tss2_tpm2_types.h:1144
type TpmsSessionAuditInfo C.TPMS_SESSION_AUDIT_INFO

// TpmsCreationInfo as declared in tss2/tss2_tpm2_types.h:1150
type TpmsCreationInfo C.TPMS_CREATION_INFO

// TpmsNvCertifyInfo as declared in tss2/tss2_tpm2_types.h:1157
type TpmsNvCertifyInfo C.TPMS_NV_CERTIFY_INFO

// TpmiStAttest type as declared in tss2/tss2_tpm2_types.h:1160
type TpmiStAttest uint16

// TpmuAttest as declared in tss2/tss2_tpm2_types.h:1171
const sizeofTpmuAttest = unsafe.Sizeof(C.TPMU_ATTEST{})

type TpmuAttest [sizeofTpmuAttest]byte

// TpmsAttest as declared in tss2/tss2_tpm2_types.h:1182
type TpmsAttest C.TPMS_ATTEST

// Tpm2bAttest as declared in tss2/tss2_tpm2_types.h:1188
type Tpm2bAttest C.TPM2B_ATTEST

// TpmsAuthCommand as declared in tss2/tss2_tpm2_types.h:1196
type TpmsAuthCommand C.TPMS_AUTH_COMMAND

// TpmsAuthResponse as declared in tss2/tss2_tpm2_types.h:1203
type TpmsAuthResponse C.TPMS_AUTH_RESPONSE

// TpmiAesKeyBits type as declared in tss2/tss2_tpm2_types.h:1206
type TpmiAesKeyBits uint16

// TpmiSm4KeyBits type as declared in tss2/tss2_tpm2_types.h:1209
type TpmiSm4KeyBits uint16

// TpmiTpm2CamelliaKeyBits type as declared in tss2/tss2_tpm2_types.h:1212
type TpmiTpm2CamelliaKeyBits uint16

// TpmuSymKeyBits as declared in tss2/tss2_tpm2_types.h:1221
const sizeofTpmuSymKeyBits = unsafe.Sizeof(C.TPMU_SYM_KEY_BITS{})

type TpmuSymKeyBits [sizeofTpmuSymKeyBits]byte

// TpmuSymMode as declared in tss2/tss2_tpm2_types.h:1229
const sizeofTpmuSymMode = unsafe.Sizeof(C.TPMU_SYM_MODE{})

type TpmuSymMode [sizeofTpmuSymMode]byte

// TpmtSymDef as declared in tss2/tss2_tpm2_types.h:1236
type TpmtSymDef C.TPMT_SYM_DEF

// TpmtSymDefObject as declared in tss2/tss2_tpm2_types.h:1243
type TpmtSymDefObject C.TPMT_SYM_DEF_OBJECT

// Tpm2bSymKey as declared in tss2/tss2_tpm2_types.h:1249
type Tpm2bSymKey C.TPM2B_SYM_KEY

// TpmsSymcipherParms as declared in tss2/tss2_tpm2_types.h:1254
type TpmsSymcipherParms C.TPMS_SYMCIPHER_PARMS

// Tpm2bSensitiveData as declared in tss2/tss2_tpm2_types.h:1260
type Tpm2bSensitiveData C.TPM2B_SENSITIVE_DATA

// TpmsSensitiveCreate as declared in tss2/tss2_tpm2_types.h:1266
type TpmsSensitiveCreate C.TPMS_SENSITIVE_CREATE

// Tpm2bSensitiveCreate as declared in tss2/tss2_tpm2_types.h:1272
type Tpm2bSensitiveCreate C.TPM2B_SENSITIVE_CREATE

// TpmsSchemeHash as declared in tss2/tss2_tpm2_types.h:1277
type TpmsSchemeHash C.TPMS_SCHEME_HASH

// TpmsSchemeEcdaa as declared in tss2/tss2_tpm2_types.h:1283
type TpmsSchemeEcdaa C.TPMS_SCHEME_ECDAA

// TpmiAlgKeyedhashScheme type as declared in tss2/tss2_tpm2_types.h:1286
type TpmiAlgKeyedhashScheme uint16

// TpmsSchemeHmac as declared in tss2/tss2_tpm2_types.h:1289
type TpmsSchemeHmac C.TPMS_SCHEME_HASH

// TpmsSchemeXor as declared in tss2/tss2_tpm2_types.h:1295
type TpmsSchemeXor C.TPMS_SCHEME_XOR

// TpmuSchemeKeyedhash as declared in tss2/tss2_tpm2_types.h:1301
const sizeofTpmuSchemeKeyedhash = unsafe.Sizeof(C.TPMU_SCHEME_KEYEDHASH{})

type TpmuSchemeKeyedhash [sizeofTpmuSchemeKeyedhash]byte

// TpmtKeyedhashScheme as declared in tss2/tss2_tpm2_types.h:1307
type TpmtKeyedhashScheme C.TPMT_KEYEDHASH_SCHEME

// TpmsSigSchemeRsassa as declared in tss2/tss2_tpm2_types.h:1310
type TpmsSigSchemeRsassa C.TPMS_SCHEME_HASH

// TpmsSigSchemeRsapss as declared in tss2/tss2_tpm2_types.h:1311
type TpmsSigSchemeRsapss C.TPMS_SCHEME_HASH

// TpmsSigSchemeEcdsa as declared in tss2/tss2_tpm2_types.h:1314
type TpmsSigSchemeEcdsa C.TPMS_SCHEME_HASH

// TpmsSigSchemeSm2 as declared in tss2/tss2_tpm2_types.h:1315
type TpmsSigSchemeSm2 C.TPMS_SCHEME_HASH

// TpmsSigSchemeEcschnorr as declared in tss2/tss2_tpm2_types.h:1316
type TpmsSigSchemeEcschnorr C.TPMS_SCHEME_HASH

// TpmsSigSchemeEcdaa as declared in tss2/tss2_tpm2_types.h:1317
type TpmsSigSchemeEcdaa C.TPMS_SCHEME_ECDAA

// TpmuSigScheme as declared in tss2/tss2_tpm2_types.h:1329
const sizeofTpmuSigScheme = unsafe.Sizeof(C.TPMU_SIG_SCHEME{})

type TpmuSigScheme [sizeofTpmuSigScheme]byte

// TpmtSigScheme as declared in tss2/tss2_tpm2_types.h:1335
type TpmtSigScheme C.TPMT_SIG_SCHEME

// TpmsEncSchemeOaep as declared in tss2/tss2_tpm2_types.h:1338
type TpmsEncSchemeOaep C.TPMS_SCHEME_HASH

// TpmsEncSchemeRsaes as declared in tss2/tss2_tpm2_types.h:1339
type TpmsEncSchemeRsaes C.TPMS_EMPTY

// TpmsKeySchemeEcdh as declared in tss2/tss2_tpm2_types.h:1342
type TpmsKeySchemeEcdh C.TPMS_SCHEME_HASH

// TpmsKeySchemeEcmqv as declared in tss2/tss2_tpm2_types.h:1343
type TpmsKeySchemeEcmqv C.TPMS_SCHEME_HASH

// TpmsSchemeMgf1 as declared in tss2/tss2_tpm2_types.h:1346
type TpmsSchemeMgf1 C.TPMS_SCHEME_HASH

// TpmsSchemeKdf1Sp80056a as declared in tss2/tss2_tpm2_types.h:1347
type TpmsSchemeKdf1Sp80056a C.TPMS_SCHEME_HASH

// TpmsSchemeKdf2 as declared in tss2/tss2_tpm2_types.h:1348
type TpmsSchemeKdf2 C.TPMS_SCHEME_HASH

// TpmsSchemeKdf1Sp800108 as declared in tss2/tss2_tpm2_types.h:1349
type TpmsSchemeKdf1Sp800108 C.TPMS_SCHEME_HASH

// TpmuKdfScheme as declared in tss2/tss2_tpm2_types.h:1357
const sizeofTpmuKdfScheme = unsafe.Sizeof(C.TPMU_KDF_SCHEME{})

type TpmuKdfScheme [sizeofTpmuKdfScheme]byte

// TpmtKdfScheme as declared in tss2/tss2_tpm2_types.h:1363
type TpmtKdfScheme C.TPMT_KDF_SCHEME

// TpmiAlgAsymScheme type as declared in tss2/tss2_tpm2_types.h:1366
type TpmiAlgAsymScheme uint16

// TpmuAsymScheme as declared in tss2/tss2_tpm2_types.h:1381
const sizeofTpmuAsymScheme = unsafe.Sizeof(C.TPMU_ASYM_SCHEME{})

type TpmuAsymScheme [sizeofTpmuAsymScheme]byte

// TpmtAsymScheme as declared in tss2/tss2_tpm2_types.h:1387
type TpmtAsymScheme C.TPMT_ASYM_SCHEME

// TpmiAlgRsaScheme type as declared in tss2/tss2_tpm2_types.h:1390
type TpmiAlgRsaScheme uint16

// TpmtRsaScheme as declared in tss2/tss2_tpm2_types.h:1396
type TpmtRsaScheme C.TPMT_RSA_SCHEME

// TpmiAlgRsaDecrypt type as declared in tss2/tss2_tpm2_types.h:1399
type TpmiAlgRsaDecrypt uint16

// TpmtRsaDecrypt as declared in tss2/tss2_tpm2_types.h:1405
type TpmtRsaDecrypt C.TPMT_RSA_DECRYPT

// Tpm2bPublicKeyRsa as declared in tss2/tss2_tpm2_types.h:1411
type Tpm2bPublicKeyRsa C.TPM2B_PUBLIC_KEY_RSA

// TpmiRsaKeyBits type as declared in tss2/tss2_tpm2_types.h:1414
type TpmiRsaKeyBits uint16

// Tpm2bPrivateKeyRsa as declared in tss2/tss2_tpm2_types.h:1420
type Tpm2bPrivateKeyRsa C.TPM2B_PRIVATE_KEY_RSA

// Tpm2bEccParameter as declared in tss2/tss2_tpm2_types.h:1426
type Tpm2bEccParameter C.TPM2B_ECC_PARAMETER

// TpmsEccPoint as declared in tss2/tss2_tpm2_types.h:1432
type TpmsEccPoint C.TPMS_ECC_POINT

// Tpm2bEccPoint as declared in tss2/tss2_tpm2_types.h:1438
type Tpm2bEccPoint C.TPM2B_ECC_POINT

// TpmiAlgEccScheme type as declared in tss2/tss2_tpm2_types.h:1441
type TpmiAlgEccScheme uint16

// TpmiEccCurve type as declared in tss2/tss2_tpm2_types.h:1444
type TpmiEccCurve uint16

// TpmtEccScheme as declared in tss2/tss2_tpm2_types.h:1450
type TpmtEccScheme C.TPMT_ECC_SCHEME

// TpmsAlgorithmDetailEcc as declared in tss2/tss2_tpm2_types.h:1465
type TpmsAlgorithmDetailEcc C.TPMS_ALGORITHM_DETAIL_ECC

// TpmsSignatureRsa as declared in tss2/tss2_tpm2_types.h:1471
type TpmsSignatureRsa C.TPMS_SIGNATURE_RSA

// TpmsSignatureRsassa as declared in tss2/tss2_tpm2_types.h:1474
type TpmsSignatureRsassa C.TPMS_SIGNATURE_RSA

// TpmsSignatureRsapss as declared in tss2/tss2_tpm2_types.h:1475
type TpmsSignatureRsapss C.TPMS_SIGNATURE_RSA

// TpmsSignatureEcc as declared in tss2/tss2_tpm2_types.h:1482
type TpmsSignatureEcc C.TPMS_SIGNATURE_ECC

// TpmsSignatureEcdsa as declared in tss2/tss2_tpm2_types.h:1485
type TpmsSignatureEcdsa C.TPMS_SIGNATURE_ECC

// TpmsSignatureEcdaa as declared in tss2/tss2_tpm2_types.h:1486
type TpmsSignatureEcdaa C.TPMS_SIGNATURE_ECC

// TpmsSignatureSm2 as declared in tss2/tss2_tpm2_types.h:1487
type TpmsSignatureSm2 C.TPMS_SIGNATURE_ECC

// TpmsSignatureEcschnorr as declared in tss2/tss2_tpm2_types.h:1488
type TpmsSignatureEcschnorr C.TPMS_SIGNATURE_ECC

// TpmuSignature as declared in tss2/tss2_tpm2_types.h:1500
const sizeofTpmuSignature = unsafe.Sizeof(C.TPMU_SIGNATURE{})

type TpmuSignature [sizeofTpmuSignature]byte

// TpmtSignature as declared in tss2/tss2_tpm2_types.h:1506
type TpmtSignature C.TPMT_SIGNATURE

// TpmuEncryptedSecret as declared in tss2/tss2_tpm2_types.h:1514
const sizeofTpmuEncryptedSecret = unsafe.Sizeof(C.TPMU_ENCRYPTED_SECRET{})

type TpmuEncryptedSecret [sizeofTpmuEncryptedSecret]byte

// Tpm2bEncryptedSecret as declared in tss2/tss2_tpm2_types.h:1520
type Tpm2bEncryptedSecret C.TPM2B_ENCRYPTED_SECRET

// TpmiAlgPublic type as declared in tss2/tss2_tpm2_types.h:1523
type TpmiAlgPublic uint16

// TpmuPublicId as declared in tss2/tss2_tpm2_types.h:1531
const sizeofTpmuPublicId = unsafe.Sizeof(C.TPMU_PUBLIC_ID{})

type TpmuPublicId [sizeofTpmuPublicId]byte

// TpmsKeyedhashParms as declared in tss2/tss2_tpm2_types.h:1536
type TpmsKeyedhashParms C.TPMS_KEYEDHASH_PARMS

// TpmsAsymParms as declared in tss2/tss2_tpm2_types.h:1542
type TpmsAsymParms C.TPMS_ASYM_PARMS

// TpmsRsaParms as declared in tss2/tss2_tpm2_types.h:1550
type TpmsRsaParms C.TPMS_RSA_PARMS

// TpmsEccParms as declared in tss2/tss2_tpm2_types.h:1558
type TpmsEccParms C.TPMS_ECC_PARMS

// TpmuPublicParms as declared in tss2/tss2_tpm2_types.h:1567
const sizeofTpmuPublicParms = unsafe.Sizeof(C.TPMU_PUBLIC_PARMS{})

type TpmuPublicParms [sizeofTpmuPublicParms]byte

// TpmtPublicParms as declared in tss2/tss2_tpm2_types.h:1573
type TpmtPublicParms C.TPMT_PUBLIC_PARMS

// TpmtPublic as declared in tss2/tss2_tpm2_types.h:1583
type TpmtPublic C.TPMT_PUBLIC

// Tpm2bPublic as declared in tss2/tss2_tpm2_types.h:1589
type Tpm2bPublic C.TPM2B_PUBLIC

// Tpm2bTemplate as declared in tss2/tss2_tpm2_types.h:1595
type Tpm2bTemplate C.TPM2B_TEMPLATE

// Tpm2bPrivateVendorSpecific as declared in tss2/tss2_tpm2_types.h:1601
type Tpm2bPrivateVendorSpecific C.TPM2B_PRIVATE_VENDOR_SPECIFIC

// TpmuSensitiveComposite as declared in tss2/tss2_tpm2_types.h:1610
const sizeofTpmuSensitiveComposite = unsafe.Sizeof(C.TPMU_SENSITIVE_COMPOSITE{})

type TpmuSensitiveComposite [sizeofTpmuSensitiveComposite]byte

// TpmtSensitive as declared in tss2/tss2_tpm2_types.h:1618
type TpmtSensitive C.TPMT_SENSITIVE

// Tpm2bSensitive as declared in tss2/tss2_tpm2_types.h:1624
type Tpm2bSensitive C.TPM2B_SENSITIVE

// Private as declared in tss2/tss2_tpm2_types.h:1631
type Private C._PRIVATE

// Tpm2bPrivate as declared in tss2/tss2_tpm2_types.h:1637
type Tpm2bPrivate C.TPM2B_PRIVATE

// TpmsIdObject as declared in tss2/tss2_tpm2_types.h:1643
type TpmsIdObject C.TPMS_ID_OBJECT

// Tpm2bIdObject as declared in tss2/tss2_tpm2_types.h:1649
type Tpm2bIdObject C.TPM2B_ID_OBJECT

// Tpm2NvIndex type as declared in tss2/tss2_tpm2_types.h:1652
type Tpm2NvIndex uint32

// Tpm2Nt type as declared in tss2/tss2_tpm2_types.h:1660
type Tpm2Nt byte

// TpmsNvPinCounterParameters as declared in tss2/tss2_tpm2_types.h:1673
type TpmsNvPinCounterParameters C.TPMS_NV_PIN_COUNTER_PARAMETERS

// TpmaNv type as declared in tss2/tss2_tpm2_types.h:1676
type TpmaNv uint32

// TpmsNvPublic as declared in tss2/tss2_tpm2_types.h:1711
type TpmsNvPublic C.TPMS_NV_PUBLIC

// Tpm2bNvPublic as declared in tss2/tss2_tpm2_types.h:1717
type Tpm2bNvPublic C.TPM2B_NV_PUBLIC

// Tpm2bContextSensitive as declared in tss2/tss2_tpm2_types.h:1723
type Tpm2bContextSensitive C.TPM2B_CONTEXT_SENSITIVE

// TpmsContextData as declared in tss2/tss2_tpm2_types.h:1729
type TpmsContextData C.TPMS_CONTEXT_DATA

// Tpm2bContextData as declared in tss2/tss2_tpm2_types.h:1735
type Tpm2bContextData C.TPM2B_CONTEXT_DATA

// TpmsContext as declared in tss2/tss2_tpm2_types.h:1743
type TpmsContext C.TPMS_CONTEXT

// TpmsCreationData as declared in tss2/tss2_tpm2_types.h:1754
type TpmsCreationData C.TPMS_CREATION_DATA

// Tpm2bCreationData as declared in tss2/tss2_tpm2_types.h:1760
type Tpm2bCreationData C.TPM2B_CREATION_DATA

// TpmAt type as declared in tss2/tss2_tpm2_types.h:1762
type TpmAt uint32

// TpmEa type as declared in tss2/tss2_tpm2_types.h:1771
type TpmEa uint32

// TpmiRhAc type as declared in tss2/tss2_tpm2_types.h:1775
type TpmiRhAc uint32

// TpmsAcOutput as declared in tss2/tss2_tpm2_types.h:1781
type TpmsAcOutput C.TPMS_AC_OUTPUT

// TpmlAcCapabilities as declared in tss2/tss2_tpm2_types.h:1787
type TpmlAcCapabilities C.TPML_AC_CAPABILITIES

// Tss2SysContext as declared in tss2/tss2_sys.h:26
type Tss2SysContext C.TSS2_SYS_CONTEXT

// Tss2lSysAuthCommand as declared in tss2/tss2_sys.h:34
type Tss2lSysAuthCommand struct {
	Count          Uint16T
	Auths          [3]TpmsAuthCommand
	reff9bbf97f    *C.TSS2L_SYS_AUTH_COMMAND
	allocsf9bbf97f interface{}
}

// Tss2lSysAuthResponse as declared in tss2/tss2_sys.h:39
type Tss2lSysAuthResponse struct {
	Count          Uint16T
	Auths          [3]TpmsAuthResponse
	ref44662040    *C.TSS2L_SYS_AUTH_RESPONSE
	allocs44662040 interface{}
}

// DivT as declared in include/stdlib.h:62
type DivT C.div_t

// LdivT as declared in include/stdlib.h:70
type LdivT C.ldiv_t

// LldivT as declared in include/stdlib.h:80
type LldivT C.lldiv_t

// Float32 type as declared in bits/floatn-common.h:214
type Float32 float32

// Float64 type as declared in bits/floatn-common.h:251
type Float64 float64

// Float32x type as declared in bits/floatn-common.h:268
type Float32x float64

// Float64x type as declared in bits/floatn-common.h:285
type Float64x float64

// UChar type as declared in sys/types.h:33
type UChar byte

// UShort type as declared in sys/types.h:34
type UShort uint16

// UInt type as declared in sys/types.h:35
type UInt uint32

// ULong type as declared in sys/types.h:36
type ULong uint32

// QuadT type as declared in sys/types.h:37
type QuadT int32

// UQuadT type as declared in sys/types.h:38
type UQuadT uint32

// FsidT as declared in sys/types.h:39
type FsidT C.__fsid_t

// LoffT type as declared in sys/types.h:42
type LoffT int32

// InoT type as declared in sys/types.h:47
type InoT uint32

// DevT type as declared in sys/types.h:59
type DevT uint32

// GidT type as declared in sys/types.h:64
type GidT uint32

// ModeT type as declared in sys/types.h:69
type ModeT uint32

// NlinkT type as declared in sys/types.h:74
type NlinkT uint32

// UidT type as declared in sys/types.h:79
type UidT uint32

// OffT type as declared in sys/types.h:85
type OffT int32

// PidT type as declared in sys/types.h:97
type PidT int32

// IdT type as declared in sys/types.h:103
type IdT uint32

// SsizeT type as declared in sys/types.h:108
type SsizeT int32

// DaddrT type as declared in sys/types.h:114
type DaddrT int32

// CaddrT type as declared in sys/types.h:115
type CaddrT []byte

// KeyT type as declared in sys/types.h:121
type KeyT int32

// Ulong type as declared in sys/types.h:148
type Ulong uint32

// Ushort type as declared in sys/types.h:149
type Ushort uint16

// Uint type as declared in sys/types.h:150
type Uint uint32

// UInt8T type as declared in sys/types.h:158
type UInt8T byte

// UInt16T type as declared in sys/types.h:159
type UInt16T uint16

// UInt32T type as declared in sys/types.h:160
type UInt32T uint32

// UInt64T type as declared in sys/types.h:161
type UInt64T uint32

// RegisterT type as declared in sys/types.h:166
type RegisterT int32

// BlksizeT type as declared in sys/types.h:185
type BlksizeT int32

// BlkcntT type as declared in sys/types.h:192
type BlkcntT int32

// FsblkcntT type as declared in sys/types.h:196
type FsblkcntT uint32

// FsfilcntT type as declared in sys/types.h:200
type FsfilcntT uint32

// ClockT type as declared in types/clock_t.h:7
type ClockT int32

// ClockidT type as declared in types/clockid_t.h:7
type ClockidT int32

// TimeT type as declared in types/time_t.h:7
type TimeT int32

// TimerT type as declared in types/timer_t.h:7
type TimerT unsafe.Pointer

// SusecondsT type as declared in sys/select.h:43
type SusecondsT int32

// FdSet as declared in sys/select.h:70
type FdSet C.fd_set

// FdMask type as declared in sys/select.h:77
type FdMask int32

// SigsetT as declared in types/sigset_t.h:7
type SigsetT C.__sigset_t

// PthreadT type as declared in bits/pthreadtypes.h:27
type PthreadT uint32

// PthreadMutexattrT as declared in bits/pthreadtypes.h:36
const sizeofPthreadMutexattrT = unsafe.Sizeof(C.pthread_mutexattr_t{})

type PthreadMutexattrT [sizeofPthreadMutexattrT]byte

// PthreadCondattrT as declared in bits/pthreadtypes.h:45
const sizeofPthreadCondattrT = unsafe.Sizeof(C.pthread_condattr_t{})

type PthreadCondattrT [sizeofPthreadCondattrT]byte

// PthreadKeyT type as declared in bits/pthreadtypes.h:49
type PthreadKeyT uint32

// PthreadOnceT type as declared in bits/pthreadtypes.h:53
type PthreadOnceT int32

// PthreadAttrT as declared in bits/pthreadtypes.h:62
const sizeofPthreadAttrT = unsafe.Sizeof(C.pthread_attr_t{})

type PthreadAttrT [sizeofPthreadAttrT]byte

// PthreadMutexT as declared in bits/pthreadtypes.h:72
const sizeofPthreadMutexT = unsafe.Sizeof(C.pthread_mutex_t{})

type PthreadMutexT [sizeofPthreadMutexT]byte

// PthreadCondT as declared in bits/pthreadtypes.h:80
const sizeofPthreadCondT = unsafe.Sizeof(C.pthread_cond_t{})

type PthreadCondT [sizeofPthreadCondT]byte

// PthreadRwlockT as declared in bits/pthreadtypes.h:91
const sizeofPthreadRwlockT = unsafe.Sizeof(C.pthread_rwlock_t{})

type PthreadRwlockT [sizeofPthreadRwlockT]byte

// PthreadRwlockattrT as declared in bits/pthreadtypes.h:97
const sizeofPthreadRwlockattrT = unsafe.Sizeof(C.pthread_rwlockattr_t{})

type PthreadRwlockattrT [sizeofPthreadRwlockattrT]byte

// PthreadSpinlockT type as declared in bits/pthreadtypes.h:103
type PthreadSpinlockT int32

// PthreadBarrierT as declared in bits/pthreadtypes.h:112
const sizeofPthreadBarrierT = unsafe.Sizeof(C.pthread_barrier_t{})

type PthreadBarrierT [sizeofPthreadBarrierT]byte

// PthreadBarrierattrT as declared in bits/pthreadtypes.h:118
const sizeofPthreadBarrierattrT = unsafe.Sizeof(C.pthread_barrierattr_t{})

type PthreadBarrierattrT [sizeofPthreadBarrierattrT]byte

// Tss2RcHandler type as declared in tss2/tss2_rc.h:10
type Tss2RcHandler func(rc Tss2Rc) *string

// ImaxdivT as declared in include/inttypes.h:275
type ImaxdivT C.imaxdiv_t
